UPP: AVIATION.f File Reference
AVIATION.f File Reference
Subroutines related to aviation.
Functions/Subroutines
subroutine calcat (U, V, H, U_OLD, V_OLD, H_OLD, CAT)
Computes Clear Air Turbulence Index.
subroutine calceiling (CLDZ, TCLD, CEILING)
Computes ceiling.
subroutine calfltcnd (CEILING, FLTCND)
Computes Ceiling.
subroutine calicing (T1, RH, OMGA, ICING)
Computes In-Flight Icing.
subroutine calllws (U, V, H, LLWS)
Computes Low Level Wind Shear (0-2000feet)
Detailed Description
Subroutines related to aviation.
Definition in file AVIATION.f.
Function/Subroutine Documentation
calcat()
subroutine calcat (real, dimension(ista_2l:iend_2u,jsta_2l:jend_2u), intent(in) U, V, H, U_OLD, V_OLD, H_OLD, CAT)
Computes Clear Air Turbulence Index.
This program computes the Clear Air Turbulence condition which is expressed as Index with Ellrod Algorithm (Gary P. Ellrod: Wea. and Forecast,1992) and Ri number suggested by S. Silberberg of AWC. But Ri number is still not classified into 3 level CAT, so current version does not use Ri as suggested by S. Silberberg.
PROGRAM HISTORY LOG:
05-09-19 H CHUANG - MODIFIED TO COMPUTE GRADIENTS FOR BOTH A AND E GRIDS
According to Ellrod, the CAT is classied into 3 levels (index):
Light: CAT = 1
- Middle: CAT = 2
Severe: CAT = 3
No CAT: CAT = 0
Parameters
[in] U U wind profile (m/s) (at pressure level)
[in] V V wind (m/s) (at pressure level)
[in] H Height (m) (at pressure level)
[in] U_OLD U wind profile (m/s) (at pressure level)
[in] V_OLD V wind (m/s) (at pressure level)
[in] H_OLD Height (m) (at pressure level)
[in,out] CAT CAT Index
Author
Binbin Zhou NCEP/EMC
Date
2005-08-16
Definition at line 265 of file AVIATION.f.
References exch().
Referenced by mdl2p().
calceiling()
subroutine calceiling (real, dimension(ista:iend,jsta:jend), intent(in) CLDZ, real, dimension(ista:iend,jsta:jend), intent(in) TCLD, real, dimension(ista:iend,jsta:jend), intent(inout) CEILING)
Computes ceiling.
This program computes the ceiling. Definition: Ceiling is the cloud base height for cloud fraction > 50% The cloud base is from sea level in the model, while ceiling is from surface. If no ceiling, set ceiling height = 20000 m
Parameters
[in] CLDZ CLOUD BASE HEIGHT from sea level(M)
[in] TCLD TOTAL CLOUD FRACTION (%)
[in,out] CEILING CEILING HEIGHT from surface (m)
Author
Binbin Zhou NCEP/EMC
Date
2005-08-18
Definition at line 497 of file AVIATION.f.
Referenced by cldrad().
calfltcnd()
subroutine calfltcnd (real, dimension(ista:iend,jsta:jend), intent(in) CEILING, real, dimension(ista:iend,jsta:jend), intent(inout) FLTCND)
Computes Ceiling.
This program computes the flight condition restriction which is defined as follow (NOAA/NWS/Instruction for TAF, 2004):
Ceiling(feet) Visibility(miles) FLTCND
LIFR < 200 and/or < 1 1
IFR >= 500 to < 1000 and/or >=1 to < 3 2
MVFR >=1000 to <= 3000 and/or >=3 to <= 5 3
VFR > 3000 > 5 5
Parameters
[in] CEILING - CEILING HEIGHT from surface (m) NOTE: VIS - Visibility is passed through COMMON /VISB/
[in,out] FLTCND - FLIGHT CONDITION CATERGORY
Author
Binbin Zhou NCEP/EMC
Date
2005-08-18
Definition at line 551 of file AVIATION.f.
Referenced by cldrad().
calicing()
subroutine calicing (real, dimension(ista:iend,jsta:jend), intent(in) T1, real, dimension(ista:iend,jsta:jend), intent(in) RH, real, dimension(ista:iend,jsta:jend), intent(in) OMGA, real, dimension(ista:iend,jsta:jend), intent(inout) ICING)
Computes In-Flight Icing.
This program computes the in-flight icing condition with the T-RH-OMGA algorithm provided by S. Silberberg of NCEP/AWC (improved new version).
According to S. Silberberg, Icing happens in following situation:
-22C < T < 0C to
2. RH > 70 %
Ascent air, OMGA < 0
Equivalent Potential Vorticity (EPV) < 0
Cloud water if SLD (supercooled large droplet)
Current version dosn't consider SLD, so cloud water
is not used. EPV computation is not available for current NCEP/EMC models(NAM, WRF, RSM), so EPV is also not used.
Parameters
[in] T1 TEMPERATURE (K)
[in] RH RELATIVE HUMIDITY (DECIMAL FORM)
[in] OMGA Vertical velocity (Pa/sec)
[in,out] ICING ICING CONDITION (1 or 0)
Author
Binbin Zhou NCEP/EMC
Date
2005-08-16
Definition at line 161 of file AVIATION.f.
Referenced by mdl2p().
calllws()
subroutine calllws (real, dimension(im,jm,lsm), intent(in) U, real, dimension(im,jm,lsm), intent(in) V, real, dimension(im,jm,lsm), intent(in) H, real, dimension(im,jm), intent(inout) LLWS)
Computes Low Level Wind Shear (0-2000feet)
This program computes the low level wind shear(LLWS) over 0-2000 feet (0-609.5m) layer. But because 10m wind represent sfc wind, 10-619.5 m layer is used. (NOAA/NWS Instruction 10-813, 2004)
Definition: LLWS(Z1,Z2) is vector difference of wind at z1 and z2 where:
Z1 = 10m + Surface height
- Z2 = 619.5 + Surface height
Algorithm: since Z2 is not defined in the model, so, first thing is searching Z2 to see which layers it is located(ie between which two pressure levels), then find the wind vector (U2,V2)at Z2 by interpolating with the wind vectors of the at pressure levels above and below then compute the vector difference between Z2 and Z1 (ie U10,V10)
      ----------------------------------------- K2-1 ---------------------
                            ^
                            |
                            |
                            |
                 ____       |  _____ Z2, U2=interpo[U(K2),U(K2-1)]
                  ^         |            V2=interpo[V(K2),V(K2-1)]
                  |         |
      ------------|---------|------------------ K2 ------------------------
                  |         |
                  |         |DH=SUM of all layers between K1-1 & K2-1
                  |         |                                            .
                  |609.5m   |                                            .
                  |(2000ft) |                                            .
                  |         v
      ------------|---------------------------------------------------- LSM-2
                  |               ^
                  |               |ZH1
                  |               |
                 o-o 10m       ___v__ Z1,U10,V10
       FIS    ....|.....          ^
        ^   .            .        |
      --|-------------------------|------------ K1 -------------------- LSM-1
        | .                .      |
        |.                  .     |
       .|                    ...  |
      --|-------------------------|------------------------------------- LSM
      . |                         |
     ////////////////////////////////////////////////////////////////// Sea Level
Parameters
[in] U U wind profile (m/s) (at pressure level).
[in] V V wind (m/s) (at pressure level).
[in] H Height (m) (at pressure level).
[out] LLWS Low level wind shear (Knots/2000ft).
Program History
- 19-10-30 Bo CUI - REMOVE "GOTO" STATEMENT
21-04-01 Jesse Meng - computation on defined points only
Author
Binbin Zhou NCEP/EMC
Date
2005-08-16
Definition at line 66 of file AVIATION.f.