UPP: CALDWP.f File Reference
CALDWP.f File Reference
Subroutine related to dewpoint temperature.
Functions/Subroutines
subroutine caldwp (P1D, Q1D, TDWP, T1D)
Computes dewpoint from P, T, and Q.
Detailed Description
Subroutine related to dewpoint temperature.
Definition in file CALDWP.f.
Function/Subroutine Documentation
caldwp()
subroutine caldwp (intent(in) P1D, intent(in) Q1D, intent(in) TDWP, intent(in) T1D)
Computes dewpoint from P, T, and Q.
Parameters
[in] P1D Pressure (Pa).
[in] Q1D Specific humidity (kg/kg).
[in] T1D Temperature (K).
[out] TDWP Dewpoint temperature (K).
Date Programmer Comments
1992-12-22 Russ Treadon Initial
1993-10-04 Russ Treadon Added check to bound dewpoint temperature to not exceed the ambient temperature.
1998-06-08 T Black Conversion from 1-D to 2-D
2000-01-04 Jim Tuccillo MPI version
2021-07-23 Wen Meng Retrict computation from undefined points
Author
Russ Treadon W/NP2
Date
1992-12-22
Definition at line 28 of file CALDWP.f.
References dewpoint().
Referenced by mdl2p(), mdlfld(), and miscln().