UPP: CALMCVG.f File Reference
CALMCVG.f File Reference
Subroutine that computes moisture convergence.
Functions/Subroutines
subroutine calmcvg (Q1D, U1D, V1D, QCNVG)
Subroutine that computes moisture convergence.
Detailed Description
Subroutine that computes moisture convergence.
 Given specific humidity, Q, and the U-V wind components
 This routine evaluates the vector operation,
                  DEL DOT (Q*VEC)
 where,
    DEL is the vector gradient operator,
    DOT is the standard dot product operator, and
    VEC is the vector wind.
 Minus one times the resulting scalar field is the
 moisture convergence which is returned by this routine.
Parameters
[in] Q1D real Specific humidity at P-points (kg/kg).
[in] U1D real U-wind component (m/s) at P-points.
[in] V1D real V-wind component (m/s) at P-points.
[out] QCNVG real Moisture convergence (1/s) at P-points.
Date Programmer Comments
1993-01-22 Russ Treadon Initial
1998-06-08 T Black Conversion From 1-D To 2-D
2000-01-04 Jim Tuccillo MPI Version
2002-04-23 Mike Baldwin WRF C-Grid Version
2005-07-07 Binbin Zhou Add RSM A Grid
2006-04-25 H Chuang Bug fixes to correctly compute MC at boundaries
2021-04-01 J Meng Computation on defined points only
2021-09-02 B CUI REPLACE EXCH_F to EXCH
2021-09-30 J MENG 2D DECOMPOSITION
Author
Russ Treadon W/NP2
Date
1993-01-22
Definition in file CALMCVG.f.
Function/Subroutine Documentation
calmcvg()
subroutine calmcvg (Q1D, U1D, V1D, QCNVG)
Subroutine that computes moisture convergence.
Parameters
[in] Q1D real Specific humidity at P-points (kg/kg).
[in] U1D real U-wind component (m/s) at P-points.
[in] V1D real V-wind component (m/s) at P-points.
[out] QCNVG real Moisture convergence (1/s) at P-points.
Definition at line 44 of file CALMCVG.f.
References exch().
Referenced by bndlyr(), mdl2p(), mdlfld(), and ngmfld().