UPP: CALRAD_WCLOUD_newcrtm.f File Reference
CALRAD_WCLOUD_newcrtm.f File Reference
Subroutine that computes model derived brightness temperature.
Functions/Subroutines
subroutine calrad_wcloud
CALRAD_WCLOUD Subroutine that computes model derived brightness temperature.
real function effr (pmid, t, q, qqw, qqi, qqr, f_rimef, nlice, nrain, qqs, qqg, qqnr, qqni, qqnw, mp_opt, species)
EFFR Computes effective particle radii channel selection using LVLS from WRF_CNTRL.PARM.
real function gammln (xx)
GAMMLN.
real function wgamma (y)
WGAMMA.
Detailed Description
Subroutine that computes model derived brightness temperature.
This routine computes model derived brightness temperature using CRTM. It is patterned after GSI setuprad with Treadon's help.
Program history log:
Date Programmer Comments
2007-01-17 H Chuang Initial
2011-02-06 Jun Wang add grib2 option
2014-12-09 WM Lewis added function EFFR to compute effective particle radii channel selection using LVLS from WRF_CNTRL.PARM
2019-04-01 Sharon Nebuda Added output option for GOES-16 & GOES-17 ABI IR Channels 7-16
2020-04-09 Tracy Hertneky Added Himawari-8 AHI CH7-CH16
2021-01-10 Wen Meng Added checking points for skiping grids with filling value spval
2021-03-11 Bo Cui improve local arrays memory
2021-08-31 Lin Zhu added ssmis-f17 channels 15-18 grib2 output
2021-09-02 Bo Cui Decompose UPP in X direction
2022-05-26 WM Lewis added support for GOES-18 ABI IR Channels 7-16
2022-09-12 Wen Meng Added cloud fraction changes for crtm/2.4.0
2023-03-22 WM Lewis Added support for using effective radius arrays from RRFS
2023-10-25 Eric James Bug fix for invalid land category in CRTM
Author
Chuang
Date
2007-01-17
Definition in file CALRAD_WCLOUD_newcrtm.f.
Function/Subroutine Documentation
calrad_wcloud()
subroutine calrad_wcloud
CALRAD_WCLOUD Subroutine that computes model derived brightness temperature.
Definition at line 28 of file CALRAD_WCLOUD_newcrtm.f.
References initpost(), ctlblk_mod::list, process(), select_channels_l(), and zensun().
Referenced by process().
effr()
real function effr (real pmid, real t, real q, real qqw, real qqi, real qqr, real f_rimef, real nlice, real nrain, real qqs, real qqg, real qqnr, real qqni, real qqnw, integer mp_opt, character(len=1) species)
EFFR Computes effective particle radii channel selection using LVLS from WRF_CNTRL.PARM.
Parameters
pmid real Mid-layer pressure.
t real Temperature.
q real Specific humidity.
qqw real Cloud water mixing ratio.
qqi real Ice mixing ratio.
qqr real Rain mixing ratio.
f_rimef real "Rime Factor", ratio of total ice growth to deposition growth.
nlice real Time-averaged number concentration of large ice.
nrain real Number concentration of rain drops.
qqs real Snow mixing ratio.
qqg real Graupel mixing ratio.
qqnr real Rain number concentration.
qqni real Ice number concentration.
qqnw real cloud water number concentration.
mp_opt integer Microphysics option.
species character Particle type (e.g., cloud, rain, graupel, snow, ice).
Returns
EFFR Effective particle radii channel selection.
Definition at line 2228 of file CALRAD_WCLOUD_newcrtm.f.
References effr(), and wgamma().
Referenced by effr().
gammln()
real function gammln (real, intent(in) xx)
GAMMLN.
Parameters
[in] XX
Returns
GAMMLN Returns the value of LN(GAMMA(XX)) FOR XX > 0.
Definition at line 2851 of file CALRAD_WCLOUD_newcrtm.f.
References gammln().
Referenced by gammln(), and wgamma().
wgamma()
real function wgamma (real, intent(in) y)
WGAMMA.
Parameters
[in] y
Returns
WGAMMA
Definition at line 2882 of file CALRAD_WCLOUD_newcrtm.f.
References gammln(), and wgamma().
Referenced by effr(), and wgamma().