UPP: CLDRAD.f File Reference
CLDRAD.f File Reference
Subroutine that posts SNDING/CLOUD/RADTN fields.
Functions/Subroutines
subroutine cb_cover (cbcov)
subroutine cldrad
CLDRAD Subroutine that computes/posts SOUNDING/CLOUD/RADIATION fields.
subroutine wrt_aero_diag (igetfld, nbin, data)
wrt_aero_diag outputs aerosol field in grib2.
Detailed Description
Subroutine that posts SNDING/CLOUD/RADTN fields.
This routine computes/posts sounding cloud related, and radiation fields. Under the heading of sounding fields fall the three ETA model lifted indices, CAPE, CIN, and total column precipitable water.
The three ETA model lifted indices differ only in the definition of the parcel to lift. One lifts parcels from the lowest above ground ETA layer. Another lifts mean
parcels from any of NBND boundary layers (See subroutine BNDLYR). The final type of lifted index is a best lifted inden based on the NBND bouddary layer lifted indices.
Two types of CAPE/CIN are available. One is based on parcels in the lowest ETA layer above ground. The other is based
on a layer mean parcel in the N-th boundary layer above the ground. See subroutine CALCAPE for details.
The cloud fraction and liquid cloud water fields are directly from the model with minimal post processing. The liquid
cloud water, 3-D cloud fraction, and temperature tendencies due to precipotation are not posted in this routine. See sunroutine ETAFLD for these fields. Lifting condensation level height and pressure are computed and posted in subroutine MISCLN.
The radiation fields posted by this routine are those computed directly in the model.
Program history log:
Date Programmer Comments
1993-08-30 Russ Treadon Initial
1994-08-04 Mike Baldwin Added output of instantaneous SFC fluxes of net SW and LW down radiation
1997-04-25 Mike Baldwin Fix PDS for precipitable water
1997-04-29 Geoff Manikin Moved cloud top temps calculation to this subroutine. Changed method of determining where cloud base and top are found and added height option for top and base
1998-04-29 Geoff Manikin Changed value for cloud base/top pressures and heights from SPVAL to -500
1998-06-15 T Black Conversion from 1-D to 2-D
1998-07-17 Mike Baldwin Removed LABL84
2000-01-04 Jim Tuccillo MPI Version
2000-02-22 Geoff Manikin Changed value for cloud base/top pressures and heights from SPVAL to -500 (was not in previous IBM version)
2001-10-22 H Chuang Modified to process hybrid model output
2002-01-15 Mike Baldwin WRF version
2005-01-06 H Chuang Add various cloud fields
2005-07-07 Binbin Zhou Add RSM model
2005-08-30 Binbin Zhou Add ceiling and flight condition restriction
2010-09-09 Geoff Manikin Revised call to CALCAPE
2011-02-06 Jun Wang Add GRIB2 Option
2011-12-14 Sarah Lu Add Aerosol optical properties
2011-12-16 Sarah Lu Add Aerosol 2D DIAG fields
2011-12-23 Sarah Lu Consolidate all GOCART fields to BLOCK 4
2011-12-23 Sarah Lu Add AOD at additional channels
2012-04-03 Jun Wang Add lftx and GFS convective cloud cover for grib2
2013-05-06 Shrinivas Moorthi Add cloud condensate to total precip water
2013-12-23 Lu/Wang Read aerosol optical properties LUTS to compute dust aod, non-dust aod, and use geos5 gocart LUTS
2015-??-?? S. Moorthi threading, optimization, local dimension
2019-07-24 Li(Kate) Zhang Merge and update ARAH Lu's work from NGAC into FV3-Chem
2019-10-30 Bo Cui Remove "GOTO" statement
2020-03-25 Jesse Meng Remove grib1
2020-05-20 Jesse Meng CALRH unification with NAM scheme
2020-11-10 Jesse Meng Use UPP_PHYSICS Module
2021-02-08 Anning Cheng read aod550, aod550_du/su/ss/oc/bc directly from fv3gfs and output to grib2 by setting rdaod
2021-04-01 Jesse Meng Computation on defined points only
2022-09-22 Li(Kate Zhang) Remove duplicated GOCART output variables and add capbility for NASA GOCART (UFS-Aerosols).
2022-09-22 Li(Kate Zhang) Update look-up table for NASA GOCART (UFS-Aerosols).
2022-10-20 Li(Kate Zhang) Add nitrate look-up table and nitrate AOD for NASA GOCART (UFS-Aerosols).
2022-11-16 Eric James Adding total column dust, biomass burning emissions, hourly wildfire potential from RRFS
2022-1207 Wen Meng Add AOD for AQM
2022-12-15 Eric James Modifying GSL exp2 ceiling diagnostic from HRRR, to correct a low bias in cloud cover
2023-02-02 Wen Meng Remove GSL specified clear-sky upward/downward SW
2023-02-10 Eric James Removing neighbourhood check from GSL exp2 ceiling diagnostic
2023-02-23 Eric James Adding coarse PM from RRFS, and using AOD from FV3 for RRFS
2023-04-04 Li(Kate Zhang) Add namelist optoin for CCPP-Chem (UFS-Chem) model.
2023-04-17 Eric James Getting rid of special treatment for RRFS AOD (use RAP/HRRR approach)
2023-09-26 Jaymes Kenyon For RRFS, use cloud fraction to diagnose cloud base/top (height and pressure)
2024-04-23 Eric James Adding smoke emissions (ebb) from RRFS
2024-05-01 Jaymes Kenyon Updates to the GSL exp-1 ceiling diagnostic
2024-05-24 Eric James Correcting the vertical summing of biomass burning emissions (EBB)
Author
Russ Treadon W/NP2
Date
1993-08-30
Definition in file CLDRAD.f.
Function/Subroutine Documentation
cb_cover()
subroutine cb_cover (real, dimension(ista:iend,jsta:jend), intent(inout) cbcov)
Parameters
[in,out] cbcov Calculate CB coverage by using fuzzy logic Evaluate membership of val in a fuzzy set fuzzy. Assume f is in x-log scale
Definition at line 5841 of file CLDRAD.f.
Referenced by cldrad().
cldrad()
subroutine cldrad
CLDRAD Subroutine that computes/posts SOUNDING/CLOUD/RADIATION fields.
Definition at line 87 of file CLDRAD.f.
References bound(), calceiling(), calfltcnd(), calpw(), cb_cover(), collect_all(), otlift(), and wrt_aero_diag().
Referenced by process().
wrt_aero_diag()
subroutine wrt_aero_diag (integer igetfld, integer nbin, real, dimension(ista_2l:iend_2u,jsta_2l:jend_2u,nbin) data)
wrt_aero_diag outputs aerosol field in grib2.
Parameters
igetfld integer UPP field ID number.
nbin integer.
data real.
Definition at line 5902 of file CLDRAD.f.
Referenced by cldrad().