#!/bin/bash

#
# configure must be run first -- configure.upp is output
if [ ! -e configure.upp ]; then
	echo "ERR :: No configure.upp file => Do './configure' first"
	exit 1
elif [ -z configure.upp ]; then
	echo "ERR :: Empty configure.upp file => Do './configure' first"
	exit 2
fi

#
# Not expecting any arguments
if [ "$#" -eq 0 ]; then
   echo "**** Compiling UPP and all libs ****"
   MAKE=`awk '($1~/^MAKE/) {print substr($0,index($0,"=")+1) }' configure.upp`
   MAKE=${MAKE:-make} # If above command returned nothing, set MAKE to "make"
   TOPDIR=$PWD
   cd sorc/comlibs
   $MAKE
   cd $TOPDIR/sorc/ncep_post.fd
   $MAKE -f makefile_dtc
   cd $TOPDIR
else
   echo "*****"
   echo " "
	echo "Unrecognized compile target $1."
   echo " "
   echo " Usage:"
   echo " compile"
   echo "   make will be called from this directory"
   echo " "
   echo "*****"
   exit 1
fi

