UPP: EXCH.f File Reference
EXCH.f File Reference
Subroutines that exchange one halo row.
Functions/Subroutines
subroutine exch (a)
exch() Subroutine that exchanges one halo row.
subroutine exch_f (a)
exch_f() Subroutine that exchanges one halo row.
Detailed Description
Subroutines that exchange one halo row.
These routines are to exchange one halo row.
Parameters
[in] A Array to have halos exchanged.
[out] A Array with halos exchanged.
Program history log:
Date Programmer Comments
2000-01-06 Jim Tuccillo Initial
2021-06-01 George Vandenberghe 2D decomposition
Note
The 1st line is an inlined compiler directive that turns off -qcheck during compilation, even if it's specified as a compiler option in the makefile (Tuccillo, personal communication; Ferrier, Feb '02).
Author
Jim Tuccillo IBM
Date
2000-01-06
Definition in file EXCH.f.
Function/Subroutine Documentation
exch()
subroutine exch (real, dimension (ista_2l:iend_2u,jsta_2l:jend_2u), intent(inout) a)
exch() Subroutine that exchanges one halo row.
Parameters
[in,out] A Array to have halos exchanged.
Note
As output, A is the array with halos exchanged.
Definition at line 26 of file EXCH.f.
References ctlblk_mod::ibcoords, and ctlblk_mod::icoords.
Referenced by bndlyr(), upp_physics::calcape2(), calcat(), upp_physics::caldiv(), upp_physics::calgradps(), calgust(), calhel(), calhel2(), calhel3(), calmcvg(), calpbl(), calpblregime(), calrch(), caltau(), calupdhel(), upp_physics::calvor(), fdlvl(), fdlvl_uv(), upp_math::h2u(), upp_math::h2v(), initpost(), initpost_gfs_nems_mpiio(), initpost_mpas(), initpost_nems(), initpost_netcdf(), mdl2agl(), mdl2p(), mdl2sigma(), mdl2thandpv(), miscln(), upp_math::u2h(), and upp_math::v2h().
exch_f()
subroutine exch_f (real, dimension (im,jsta_2l:jend_2u), intent(inout) a)
exch_f() Subroutine that exchanges one halo row.
Note
The 1st line is an inlined compiler directive that turns off -qcheck during compilation, even if it's specified as a compiler option in the makefile (Tuccillo, personal communication; Ferrier, Feb '02).
Author
Jim Tuccillo IBM
Date
2000-01-06
Parameters
[in,out] A Array to have halos exchanged.
Note
As output, A is the array with halos exchanged.
Definition at line 429 of file EXCH.f.