UPP: GFIP3.f File Reference
GFIP3.f File Reference
This file contains a collection of UPP modules used to calculate icing probability from the model.
Data Types
type cloudlayers::clouds_t
_____?
type severitymaps::scenarios_t
Functions/Subroutines
subroutine, public derivedfields::derive_fields (imp_physics, t, rh, pres, hgt, totalwater, totalcond, nz, topok, hprcp, hcprcp, cin, cape, ept, wbt, twp, pc, kx, lx, tott, prcptype)
derive_fields() Calculates several derived fields.
integer function gettopok (hgt, alt, nz)
getTopoK() Maps the topography height to the model's vertical coordinate
subroutine, public icingseverity::icing_sev (imp_physics, hgt, rh, t, pres, vv, liqcond, icecond, twp, ice_pot, nz, hcprcp, cape, lx, kx, tott, pc, prcptype, clouds, iseverity)
icing_sev() Calculates icing severity.
elemental real function, public derivedfields::mixing_ratio (td, pres)
mixing_ratio() Calculates the mixing ratio in g/kg = water vapor/dry air.
Detailed Description
This file contains a collection of UPP modules used to calculate icing probability from the model.
Definition in file GFIP3.f.
Function/Subroutine Documentation
derive_fields()
subroutine, public derivedfields::derive_fields (integer, intent(in) imp_physics, real, dimension(nz), intent(in) t, real, dimension(nz), intent(in) rh, real, dimension(nz), intent(in) pres, real, dimension(nz), intent(in) hgt, real, dimension(nz), intent(in) totalwater, real, dimension(nz), intent(in) totalcond, integer, intent(in) nz, integer, intent(in) topok, real, intent(in) hprcp, real, intent(in) hcprcp, real, intent(in) cin, real, intent(in) cape, real, dimension(nz), intent(out) ept, real, dimension(nz), intent(out) wbt, real, dimension(nz), intent(out) twp, real, intent(out) pc, real, intent(out) kx, real, intent(out) lx, real, intent(out) tott, integer, intent(out) prcptype)
derive_fields() Calculates several derived fields.
Parameters
[in] imp_physics integer Microphysics option used in the model run.
[in] t real Temperature (K).
[in] rh real Relative humidity.
[in] pres real Pressure (Pa).
[in] hgt real Height.
[in] totalWater real _____?
[in] totalCond real Precipitation Condensate in g/kg.
[in] nz integer Number of vertical levels.
[in] topoK integer _____?
[in] hprcp real Hourly accumulated precipitation.
[in] hcprcp real Hourly accumulated convective precipitation.
[in] cin real Convective inhibition (CIN).
[in] cape real Convective Available Potential Energy (CAPE)
3-D derived data:
Parameters
[out] ept real Equivalent potential temperature
[out] wbt real Wet bulb temperature
[out] twp real Total water path
2-D derived data: (indice for convective icing severity)
Parameters
[out] kx real k index
[out] lx real Lifted index
[out] tott real Total totals
2-D derived data:
Parameters
[out] pc real Precipitation condensate
[out] prcpType integer Surface precipitation type
Definition at line 64 of file GFIP3.f.
gettopok()
integer function gettopok (real, dimension(nz), intent(in) hgt, real, intent(in) alt, integer, intent(in) nz)
getTopoK() Maps the topography height to the model's vertical coordinate
Parameters
[in] hgt real Geopotential height (m).
[in] alt real Topography height (m).
[in] nz integer Number of vertical levels.
Returns
getTopoK Mapping of the topography height to the model's vertical coordinates
Definition at line 2449 of file GFIP3.f.
References gettopok().
Referenced by gettopok(), and icingseverity::icing_sev().
icing_sev()
subroutine, public icingseverity::icing_sev (integer, intent(in) imp_physics, real, dimension(nz), intent(in) hgt, real, dimension(nz), intent(in) rh, real, dimension(nz), intent(in) t, real, dimension(nz), intent(in) pres, real, dimension(nz), intent(in) vv, real, dimension(nz), intent(in) liqcond, real, dimension(nz), intent(in) icecond, real, dimension(nz), intent(in) twp, real, dimension(nz), intent(in) ice_pot, integer, intent(in) nz, real, intent(in) hcprcp, real, intent(in) cape, real, intent(in) lx, real, intent(in) kx, real, intent(in) tott, real, intent(in) pc, integer, intent(in) prcptype, type(clouds_t), intent(in) clouds, real, dimension(nz), intent(out) iseverity)
icing_sev() Calculates icing severity.
Parameters
[in] imp_physics integer Microphysics scheme.
[in] hgt real Geopotential height (m).
[in] rh real Relative humidity.
[in] t real Temperature.
[in] pres real Pressure.
[in] vv real Vertical velocity.
[in] liqCond real
[in] iceCond real
[in] twp real Total water path.
[in] ice_pot real Icing potential.
[in] nz integer Number of vertical levels.
[in] hcprcp real Hourly accumulated convective precipitation.
[in] cape real Convective Available Potential Energy (CAPE)
[in] lx real Lifted index.
[in] kx real k index.
[in] tott real Total totals.
[in] pc real Precipitation condensate.
[in] prcpType integer Surface precipitation type.
[in] clouds
[out] iseverity real Category of icing severity.
Definition at line 1660 of file GFIP3.f.
References gettopok().
mixing_ratio()
elemental real function, public derivedfields::mixing_ratio (real, intent(in) td, real, intent(in) pres)
mixing_ratio() Calculates the mixing ratio in g/kg = water vapor/dry air.
Parameters
[in] td real dew point temperture (K).
[in] pres real Pressure (Pa).
Returns
mixing_ratio
Definition at line 187 of file GFIP3.f.