UPP: Calculate secondary constants from the primary constants above
Calculate secondary constants from the primary constants above
real(kind=kind_phys), parameter physcons_post::con_rocp = con_rd / con_cp
Calculate secondary constants from the primary constants above.
real(kind=kind_phys), parameter physcons_post::con_cpor = con_cp / con_rd
Calculate secondary constants from the primary constants above.
real(kind=kind_phys), parameter physcons_post::con_rog = con_rd / con_g
Calculate secondary constants from the primary constants above.
real(kind=kind_phys), parameter physcons_post::con_fvirt = con_rv / con_rd - 1.
Calculate secondary constants from the primary constants above.
real(kind=kind_phys), parameter physcons_post::con_eps = con_rd / con_rv
Calculate secondary constants from the primary constants above.
real(kind=kind_phys), parameter physcons_post::con_epsm1 = con_rd / con_rv - 1.
Calculate secondary constants from the primary constants above.
real(kind=kind_phys), parameter physcons_post::con_dldt = con_cvap - con_cliq
Calculate secondary constants from the primary constants above.
real(kind=kind_phys), parameter physcons_post::con_xpona = con_dldt / con_rv
Calculate secondary constants from the primary constants above.
real(kind=kind_phys), parameter physcons_post::con_xponb = -con_dldt / con_rv + con_hvap / (con_rv * con_ttp)
Calculate secondary constants from the primary constants above.
Detailed Description
Variable Documentation
con_cpor
real(kind=kind_phys), parameter physcons_post::con_cpor = con_cp / con_rd
Calculate secondary constants from the primary constants above.
Definition at line 42 of file physcons.f.
con_dldt
real(kind=kind_phys), parameter physcons_post::con_dldt = con_cvap - con_cliq
Calculate secondary constants from the primary constants above.
Definition at line 47 of file physcons.f.
con_eps
real(kind=kind_phys), parameter physcons_post::con_eps = con_rd / con_rv
Calculate secondary constants from the primary constants above.
Definition at line 45 of file physcons.f.
Referenced by bndlyr(), fdlvl_mass(), frzlvl(), frzlvl2(), initpost_gfs_nems_mpiio(), initpost_netcdf(), lfmfld(), mdl2p(), mdl2thandpv(), and surfce().
con_epsm1
real(kind=kind_phys), parameter physcons_post::con_epsm1 = con_rd / con_rv - 1.
Calculate secondary constants from the primary constants above.
Definition at line 46 of file physcons.f.
Referenced by bndlyr(), fdlvl_mass(), frzlvl(), frzlvl2(), initpost_gfs_nems_mpiio(), initpost_netcdf(), lfmfld(), mdl2p(), mdl2thandpv(), and surfce().
con_fvirt
real(kind=kind_phys), parameter physcons_post::con_fvirt = con_rv / con_rd - 1.
Calculate secondary constants from the primary constants above.
Definition at line 44 of file physcons.f.
Referenced by fdlvl_mass(), icingseverity::icing_sev(), initpost_gfs_nems_mpiio(), initpost_netcdf(), mdl2p(), and rtsig().
con_rocp
real(kind=kind_phys), parameter physcons_post::con_rocp = con_rd / con_cp
Calculate secondary constants from the primary constants above.
Definition at line 41 of file physcons.f.
Referenced by pvetc().
con_rog
real(kind=kind_phys), parameter physcons_post::con_rog = con_rd / con_g
Calculate secondary constants from the primary constants above.
Definition at line 43 of file physcons.f.
Referenced by fdlvl_mass(), mdl2p(), mxwind(), p2pv(), and tpause().
con_xpona
real(kind=kind_phys), parameter physcons_post::con_xpona = con_dldt / con_rv
Calculate secondary constants from the primary constants above.
Definition at line 48 of file physcons.f.
con_xponb
real(kind=kind_phys), parameter physcons_post::con_xponb = -con_dldt / con_rv + con_hvap / (con_rv * con_ttp)
Calculate secondary constants from the primary constants above.
Definition at line 49 of file physcons.f.