UPP: xml_perl_data
xml_perl_data
Sets parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
Data Types
type xml_perl_data::param_t
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
type xml_perl_data::paramset_t
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
type xml_perl_data::post_avblfld_t
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
integer xml_perl_data::nfcst
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
integer xml_perl_data::nbc
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
integer xml_perl_data::list
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
integer xml_perl_data::iout
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
integer xml_perl_data::ntstm
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
integer xml_perl_data::nrads
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
integer xml_perl_data::nradl
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
integer xml_perl_data::nddamp
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
integer xml_perl_data::idtad
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
integer xml_perl_data::nboco
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
integer xml_perl_data::nshde
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
integer xml_perl_data::ncp
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
integer xml_perl_data::imdlty
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
character(len=50) xml_perl_data::paramset_t::type_ens_fcst =''
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
character(len=50) xml_perl_data::paramset_t::type_derived_fcst =''
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
type(param_t), dimension(:), pointer xml_perl_data::paramset_t::param => null()
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
type(paramset_t), dimension(:), pointer xml_perl_data::paramset
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
type(post_avblfld_t), save xml_perl_data::post_avblflds
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
Detailed Description
Sets parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
Data Type Documentation
xml_perl_data::param_t
type xml_perl_data::param_t
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
Definition at line 32 of file xml_perl_data.f.
Data Fields
character(len=80) aerosol_type =''
real, dimension(:) dimension
character(len=80) fixed_sfc2_type =''
real, dimension(:), pointer level => null()
real, dimension(:), pointer level2 => null()
real pointer
character(len=80) prob_type ='' haracter(len=80) :: typ_intvl_size=''
real scale => null() nteger :: stat_miss_val=0 nteger :: leng_time_range_prev=0 nteger :: time_inc_betwn_succ_fld=0 haracter(len=80) :: type_of_time_inc='' haracter(len=20) :: stat_unit_time_key_succ='' haracter(len=20) :: bit_map_flag=''
integer scale_fact_1st_size =0 eal :: scale_val_1st_size=0.0 nteger :: scale_fact_2nd_size=0 eal :: scale_val_2nd_size=0.0 haracter(len=80) :: typ_intvl_wvlen='' nteger :: scale_fact_1st_wvlen=0 eal :: scale_val_1st_wvlen=0.0 nteger :: scale_fact_2nd_wvlen=0 eal :: scale_val_2nd_wvlen=0.0
integer, dimension(:), pointer scale_fact_fixed_sfc1 => null()
integer, dimension(:), pointer scale_fact_fixed_sfc2 => null()
integer scale_fact_lower_limit =0
integer scale_fact_upper_limit =0
real scale_val_lower_limit =0.0
real scale_val_upper_limit =0.0 eal
xml_perl_data::paramset_t
type xml_perl_data::paramset_t
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
Definition at line 76 of file xml_perl_data.f.
Data Fields
type(param_t), dimension(:), pointer param => null() Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
character(len=50) type_derived_fcst ='' Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
character(len=50) type_ens_fcst ='' Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
xml_perl_data::post_avblfld_t
type xml_perl_data::post_avblfld_t
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
Definition at line 105 of file xml_perl_data.f.
Data Fields
type(param_t), dimension(:), pointer param => null()
Variable Documentation
idtad
integer xml_perl_data::idtad
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
Definition at line 25 of file xml_perl_data.f.
imdlty
integer xml_perl_data::imdlty
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
Definition at line 25 of file xml_perl_data.f.
iout
integer xml_perl_data::iout
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
Definition at line 25 of file xml_perl_data.f.
list
integer xml_perl_data::list
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
Definition at line 25 of file xml_perl_data.f.
nbc
integer xml_perl_data::nbc
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
Definition at line 25 of file xml_perl_data.f.
nboco
integer xml_perl_data::nboco
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
Definition at line 25 of file xml_perl_data.f.
ncp
integer xml_perl_data::ncp
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
Definition at line 25 of file xml_perl_data.f.
nddamp
integer xml_perl_data::nddamp
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
Definition at line 25 of file xml_perl_data.f.
nfcst
integer xml_perl_data::nfcst
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
Definition at line 25 of file xml_perl_data.f.
nradl
integer xml_perl_data::nradl
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
Definition at line 25 of file xml_perl_data.f.
nrads
integer xml_perl_data::nrads
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
Definition at line 25 of file xml_perl_data.f.
nshde
integer xml_perl_data::nshde
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
Definition at line 25 of file xml_perl_data.f.
ntstm
integer xml_perl_data::ntstm
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
Definition at line 25 of file xml_perl_data.f.
param
type(param_t), dimension(:), pointer xml_perl_data::paramset_t::param => null()
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
Definition at line 99 of file xml_perl_data.f.
paramset
type (paramset_t), dimension(:), pointer xml_perl_data::paramset
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
Definition at line 113 of file xml_perl_data.f.
Referenced by xml_perl_data::read_postxconfig(), read_xml(), and set_outflds().
post_avblflds
type (post_avblfld_t), save xml_perl_data::post_avblflds
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
Definition at line 114 of file xml_perl_data.f.
Referenced by xml_perl_data::read_postxconfig(), read_xml(), and set_outflds().
type_derived_fcst
character(len=50) xml_perl_data::paramset_t::type_derived_fcst =''
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
Definition at line 98 of file xml_perl_data.f.
type_ens_fcst
character(len=50) xml_perl_data::paramset_t::type_ens_fcst =''
Parameters that are used to read in Perl XML processed flat file and handle parameter marshalling for existing POST program.
Definition at line 97 of file xml_perl_data.f.