UPP: CTLBLK_mod
CTLBLK_mod
Sets default parameters that are used throughout the UPP code.
integer ctlblk_mod::nfcst
No longer used/supported.
integer ctlblk_mod::nbc
No longer used/supported.
integer ctlblk_mod::list
No longer used/supported.
integer ctlblk_mod::iout
No longer used/supported.
integer ctlblk_mod::ntstm
No longer used/supported.
integer ctlblk_mod::nrads
No longer used/supported.
integer ctlblk_mod::nradl
No longer used/supported.
integer ctlblk_mod::nddamp
No longer used/supported.
integer ctlblk_mod::idtad
No longer used/supported.
integer ctlblk_mod::nboco
No longer used/supported.
integer ctlblk_mod::nshde
No longer used/supported.
integer ctlblk_mod::ncp
No longer used/supported.
integer ctlblk_mod::imdlty
No longer used/supported.
integer, dimension(:,:), allocatable ctlblk_mod::icoords
Arrays that store the coordinates of their elements; used to validate communications; when scattered or otherwise dispersed, the receiving ranks check that the values of the arrays match the I and J indices of the receiver.
integer, dimension(:,:), allocatable ctlblk_mod::ibcoords
Arrays that store the coordinates of their elements; used to validate communications; when scattered or otherwise dispersed, the receiving ranks check that the values of the arrays match the I and J indices of the receiver.
real, dimension(:,:), allocatable ctlblk_mod::rcoords
Arrays that store the coordinates of their elements; used to validate communications; when scattered or otherwise dispersed, the receiving ranks check that the values of the arrays match the I and J indices of the receiver.
real, dimension(:,:), allocatable ctlblk_mod::rbcoords
Arrays that store the coordinates of their elements; used to validate communications; when scattered or otherwise dispersed, the receiving ranks check that the values of the arrays match the I and J indices of the receiver.
real(kind=8) ctlblk_mod::etafld2_tim =0.
Time to execute named routine; note that ETAFLD2 and ETA2P refer to MDLFLD and MDL2P routines respectively.
real(kind=8) ctlblk_mod::eta2p_tim =0.
Time to execute named routine; note that ETAFLD2 and ETA2P refer to MDLFLD and MDL2P routines respectively.
real(kind=8) ctlblk_mod::surfce2_tim =0.
Time to execute named routine; note that ETAFLD2 and ETA2P refer to MDLFLD and MDL2P routines respectively.
real(kind=8) ctlblk_mod::cldrad_tim =0.
Time to execute named routine; note that ETAFLD2 and ETA2P refer to MDLFLD and MDL2P routines respectively.
real(kind=8) ctlblk_mod::miscln_tim =0.
Time to execute named routine; note that ETAFLD2 and ETA2P refer to MDLFLD and MDL2P routines respectively.
real(kind=8) ctlblk_mod::fixed_tim =0.
Time to execute named routine; note that ETAFLD2 and ETA2P refer to MDLFLD and MDL2P routines respectively.
real(kind=8) ctlblk_mod::mdl2sigma_tim =0.
Time to execute named routine; note that ETAFLD2 and ETA2P refer to MDLFLD and MDL2P routines respectively.
real(kind=8) ctlblk_mod::readxml_tim =0.
Time to execute named routine; note that ETAFLD2 and ETA2P refer to MDLFLD and MDL2P routines respectively.
real(kind=8) ctlblk_mod::mdl2agl_tim =0.
Time to execute named routine; note that ETAFLD2 and ETA2P refer to MDLFLD and MDL2P routines respectively.
real(kind=8) ctlblk_mod::mdl2std_tim =0.
Time to execute named routine; note that ETAFLD2 and ETA2P refer to MDLFLD and MDL2P routines respectively.
real(kind=8) ctlblk_mod::mdl2thandpv_tim =0.
Time to execute named routine; note that ETAFLD2 and ETA2P refer to MDLFLD and MDL2P routines respectively.
real(kind=8) ctlblk_mod::calrad_wcloud_tim =0.
Time to execute named routine; note that ETAFLD2 and ETA2P refer to MDLFLD and MDL2P routines respectively.
real(kind=8) ctlblk_mod::run_ifi_tim =0.
Time to execute named routine; note that ETAFLD2 and ETA2P refer to MDLFLD and MDL2P routines respectively.
real(kind=8) ctlblk_mod::time_output =0.
Initialized as 0, but never used.
real(kind=8) ctlblk_mod::time_e2out =0.
Initialized as 0, but never used.
Detailed Description
Sets default parameters that are used throughout the UPP code.
Variable Documentation
calrad_wcloud_tim
real(kind=8) ctlblk_mod::calrad_wcloud_tim =0.
Time to execute named routine; note that ETAFLD2 and ETA2P refer to MDLFLD and MDL2P routines respectively.
Definition at line 210 of file CTLBLK.f.
Referenced by process(), and wrfpost().
cldrad_tim
real(kind=8) ctlblk_mod::cldrad_tim =0.
Time to execute named routine; note that ETAFLD2 and ETA2P refer to MDLFLD and MDL2P routines respectively.
Definition at line 210 of file CTLBLK.f.
Referenced by process(), and wrfpost().
eta2p_tim
real(kind=8) ctlblk_mod::eta2p_tim =0.
Time to execute named routine; note that ETAFLD2 and ETA2P refer to MDLFLD and MDL2P routines respectively.
Definition at line 210 of file CTLBLK.f.
Referenced by process(), and wrfpost().
etafld2_tim
real(kind=8) ctlblk_mod::etafld2_tim =0.
Time to execute named routine; note that ETAFLD2 and ETA2P refer to MDLFLD and MDL2P routines respectively.
Definition at line 210 of file CTLBLK.f.
Referenced by process(), and wrfpost().
fixed_tim
real(kind=8) ctlblk_mod::fixed_tim =0.
Time to execute named routine; note that ETAFLD2 and ETA2P refer to MDLFLD and MDL2P routines respectively.
Definition at line 210 of file CTLBLK.f.
Referenced by process(), and wrfpost().
ibcoords
integer, dimension(:,:), allocatable ctlblk_mod::ibcoords
Arrays that store the coordinates of their elements; used to validate communications; when scattered or otherwise dispersed, the receiving ranks check that the values of the arrays match the I and J indices of the receiver.
Definition at line 178 of file CTLBLK.f.
Referenced by exch(), exch_c_float(), fullpole(), and mpi_first().
icoords
integer, dimension(:,:), allocatable ctlblk_mod::icoords
Arrays that store the coordinates of their elements; used to validate communications; when scattered or otherwise dispersed, the receiving ranks check that the values of the arrays match the I and J indices of the receiver.
Definition at line 177 of file CTLBLK.f.
Referenced by exch(), exch_c_float(), fullpole(), and mpi_first().
idtad
integer ctlblk_mod::idtad
No longer used/supported.
Definition at line 105 of file CTLBLK.f.
imdlty
integer ctlblk_mod::imdlty
No longer used/supported.
Definition at line 105 of file CTLBLK.f.
iout
integer ctlblk_mod::iout
No longer used/supported.
Definition at line 105 of file CTLBLK.f.
list
integer ctlblk_mod::list
No longer used/supported.
Definition at line 105 of file CTLBLK.f.
mdl2agl_tim
real(kind=8) ctlblk_mod::mdl2agl_tim =0.
Time to execute named routine; note that ETAFLD2 and ETA2P refer to MDLFLD and MDL2P routines respectively.
Definition at line 210 of file CTLBLK.f.
Referenced by process(), and wrfpost().
mdl2sigma_tim
real(kind=8) ctlblk_mod::mdl2sigma_tim =0.
Time to execute named routine; note that ETAFLD2 and ETA2P refer to MDLFLD and MDL2P routines respectively.
Definition at line 210 of file CTLBLK.f.
Referenced by process(), and wrfpost().
mdl2std_tim
real(kind=8) ctlblk_mod::mdl2std_tim =0.
Time to execute named routine; note that ETAFLD2 and ETA2P refer to MDLFLD and MDL2P routines respectively.
Definition at line 210 of file CTLBLK.f.
Referenced by wrfpost().
mdl2thandpv_tim
real(kind=8) ctlblk_mod::mdl2thandpv_tim =0.
Time to execute named routine; note that ETAFLD2 and ETA2P refer to MDLFLD and MDL2P routines respectively.
Definition at line 210 of file CTLBLK.f.
Referenced by process(), and wrfpost().
miscln_tim
real(kind=8) ctlblk_mod::miscln_tim =0.
Time to execute named routine; note that ETAFLD2 and ETA2P refer to MDLFLD and MDL2P routines respectively.
Definition at line 210 of file CTLBLK.f.
Referenced by process(), and wrfpost().
nbc
integer ctlblk_mod::nbc
No longer used/supported.
Definition at line 105 of file CTLBLK.f.
nboco
integer ctlblk_mod::nboco
No longer used/supported.
Definition at line 105 of file CTLBLK.f.
ncp
integer ctlblk_mod::ncp
No longer used/supported.
Definition at line 105 of file CTLBLK.f.
nddamp
integer ctlblk_mod::nddamp
No longer used/supported.
Definition at line 105 of file CTLBLK.f.
nfcst
integer ctlblk_mod::nfcst
No longer used/supported.
Definition at line 105 of file CTLBLK.f.
nradl
integer ctlblk_mod::nradl
No longer used/supported.
Definition at line 105 of file CTLBLK.f.
nrads
integer ctlblk_mod::nrads
No longer used/supported.
Definition at line 105 of file CTLBLK.f.
nshde
integer ctlblk_mod::nshde
No longer used/supported.
Definition at line 105 of file CTLBLK.f.
ntstm
integer ctlblk_mod::ntstm
No longer used/supported.
Definition at line 105 of file CTLBLK.f.
rbcoords
real, dimension(:,:), allocatable ctlblk_mod::rbcoords
Arrays that store the coordinates of their elements; used to validate communications; when scattered or otherwise dispersed, the receiving ranks check that the values of the arrays match the I and J indices of the receiver.
Definition at line 180 of file CTLBLK.f.
Referenced by fullpole(), and mpi_first().
rcoords
real, dimension(:,:), allocatable ctlblk_mod::rcoords
Arrays that store the coordinates of their elements; used to validate communications; when scattered or otherwise dispersed, the receiving ranks check that the values of the arrays match the I and J indices of the receiver.
Definition at line 179 of file CTLBLK.f.
Referenced by mpi_first().
readxml_tim
real(kind=8) ctlblk_mod::readxml_tim =0.
Time to execute named routine; note that ETAFLD2 and ETA2P refer to MDLFLD and MDL2P routines respectively.
Definition at line 210 of file CTLBLK.f.
Referenced by wrfpost().
run_ifi_tim
real(kind=8) ctlblk_mod::run_ifi_tim =0.
Time to execute named routine; note that ETAFLD2 and ETA2P refer to MDLFLD and MDL2P routines respectively.
Definition at line 210 of file CTLBLK.f.
Referenced by process(), and wrfpost().
surfce2_tim
real(kind=8) ctlblk_mod::surfce2_tim =0.
Time to execute named routine; note that ETAFLD2 and ETA2P refer to MDLFLD and MDL2P routines respectively.
Definition at line 210 of file CTLBLK.f.
Referenced by process(), and wrfpost().
time_e2out
real(kind=8) ctlblk_mod::time_e2out =0.
Initialized as 0, but never used.
Definition at line 220 of file CTLBLK.f.
time_output
real(kind=8) ctlblk_mod::time_output =0.
Initialized as 0, but never used.
Definition at line 220 of file CTLBLK.f.
Referenced by wrfpost().