UPP: INITPOST_GFS_NEMS_MPIIO.f File Reference
INITPOST_GFS_NEMS_MPIIO.f File Reference
initpost_gfs_nems_mpiio() initializes post for run.
Functions/Subroutines
subroutine gg2rg (im, jm, numi, a)
gg2rg() No longer used/supported.
subroutine initpost_gfs_nems_mpiio (iostatusAER)
initializes constants and variables at the start of GFS model or post processor run.
subroutine intlon (iord, imsk, m1, m2, k1, f1, f2)
intlon() No longer used/supported.
subroutine rg2gg (im, jm, numi, a)
rg2gg() No longer used/supported.
subroutine uninterpred (iord, kmsk, lonsperlat, lonr, latr, fi, f)
uninterpred () No longer used/supported.
Detailed Description
initpost_gfs_nems_mpiio() initializes post for run.
Author
Hui-Ya Chuang
Date
2007-03-04
This routine initializes constants and variables at the start of GFS model or post processor run.
Date Programmer Comments
2007-03-04 Hui-Ya Chuang Initial
2011-02-07 Jun Wang Add grib2 option
2011-12-14 Sarah Lu Add aer option
2012-01-07 Sarah Lu Compute air density
2012-12-22 Sarah Lu Add aerosol zerout option
2015-03-16 S. Moorthi Adding gocart_on option
2015-03-18 S. Moorthi Optimization including threading
2015-08-17 S. Moorthi Add TKE for NEMS/GSM
2016-03-04 H Chuang Add MPI IO option to read GFS nems output
2016-05-16 S. Kar Add computation of omega
2016-07-21 S. Moorthi Convert input upper air data from reduced to full grid and reduce memory in divergence calculatiom
2016-07-21 Jun Wang Change averaged field name with suffix
2019-07-24 Li(Kate) Zhang Merge and update NGAC UPP into FV3-Chem
2021-03-11 Bo Cui Change local arrays to dimension (im,jsta:jend)
2022-09-22 Li(Kate) Zhang Remove duplicated initializations which have been done in ALLCOCATE_ALL.f
2023-04-04 Li(Kate Zhang) Add namelist optoin for CCPP-Chem (UFS-Chem)
Definition in file INITPOST_GFS_NEMS_MPIIO.f.
Function/Subroutine Documentation
gg2rg()
subroutine gg2rg (integer, intent(in) im, integer, intent(in) jm, integer, dimension(jm), intent(in) numi, real, dimension(im,jm), intent(inout) a)
gg2rg() No longer used/supported.
Parameters
[in] im integer No longer used/supported.
[in] jm integer No longer used/supported.
[in] numi integer No longer used/supported.
[in,out] a real No longer used/supported.
Definition at line 4080 of file INITPOST_GFS_NEMS_MPIIO.f.
Referenced by initpost_gfs_nems_mpiio().
initpost_gfs_nems_mpiio()
subroutine initpost_gfs_nems_mpiio (integer, intent(in) iostatusAER)
initializes constants and variables at the start of GFS model or post processor run.
Author
Hui-Ya Chuang
Date
2007-03-04
Parameters
[in] iostatusAER integer Status of GFS aer file.
Definition at line 39 of file INITPOST_GFS_NEMS_MPIIO.f.
References collect_loc(), physcons_post::con_eps, physcons_post::con_epsm1, physcons_post::con_fvirt, exch(), gg2rg(), modstuff2(), msfps(), and uninterpred().
Referenced by wrfpost().
intlon()
subroutine intlon (integer, intent(in) iord, integer, intent(in) imsk, integer, intent(in) m1, integer, intent(in) m2, integer, dimension(m1), intent(in) k1, real, dimension(m1), intent(in) f1, real, dimension(m2), intent(out) f2)
intlon() No longer used/supported.
Parameters
[in] iord integer No longer used/supported.
[in] imsk integer No longer used/supported.
[in] m1 integer No longer used/supported.
[in] m2 integer No longer used/supported.
[in] k1 integer No longer used/supported.
[in] f1 real No longer used/supported.
[out] f2 real No longer used/supported.
Definition at line 4143 of file INITPOST_GFS_NEMS_MPIIO.f.
Referenced by uninterpred().
rg2gg()
subroutine rg2gg (integer, intent(in) im, integer, intent(in) jm, integer, dimension(jm), intent(in) numi, real, dimension(im,jm), intent(inout) a)
rg2gg() No longer used/supported.
Parameters
[in] im integer No longer used/supported.
[in] jm integer No longer used/supported.
[in] numi integer No longer used/supported.
[in,out] a real No longer used/supported.
Definition at line 4052 of file INITPOST_GFS_NEMS_MPIIO.f.
uninterpred()
subroutine uninterpred (integer, intent(in) iord, integer, dimension(lonr,latr), intent(in) kmsk, integer, dimension(latr), intent(in) lonsperlat, integer, intent(in) lonr, integer, intent(in) latr, real, dimension(lonr,latr), intent(in) fi, real, dimension(lonr,latr), intent(out) f)
uninterpred () No longer used/supported.
Parameters
[in] iord integer No longer used/supported.
[in] kmsk integer No longer used/supported.
[in] lonsperlat integer No longer used/supported.
[in] lonr integer No longer used/supported.
[in] latr integer No longer used/supported.
[in] fi real No longer used/supported.
[out] f real No longer used/supported.
Definition at line 4111 of file INITPOST_GFS_NEMS_MPIIO.f.
References intlon().
Referenced by initpost_gfs_nems_mpiio().