UPP: INITPOST_NETCDF.f File Reference
INITPOST_NETCDF.f File Reference
initpost_netcdf() initializes post for run.
Functions/Subroutines
subroutine initpost_netcdf (ncid2d, ncid3d)
2023-04-17 | Eric James | Read in unified ext550 extinction (and remove aodtot) for RRFS 2023-04-21 | Eric James | Read in / calculate some fields needed for GSL p-type diagnosis for RRFS 2023-05-31 | Wen Meng | Bug fix in qrmax initialization 2023-06-14 | Wen Meng | Bug fix of reading seaswtc and modification of sndepac calculation 2023-07-06 | Eric James | Read in SOILL on 9 levels for RRFS 2023-07-24 | Hui-Ya Chuang | Bug fix in tke inialization 2023-08-04 | Jaymes Kenyon | Read RRFS microphysics number concentrations (cloud water, cloud ice, rain) 2023-08-31 | Li(Kate Zhang)| Add condition to include/exclude processing nitrate from model output 2023-09-22 | Wen Meng | Bug fix in cwm initialization 2023-10-17 | Eric James | Including hail mixing ratio in calculation of hydrometeor VIL and cwm when present (NSSL microphysics) 2023-10-23 | Jaymes Kenyon | Read HAILCAST diagnostic output from RRFS 2024-01-12 | Wen Meng | Remove the hard-wired bucket for beyond F240 2024-02-07 | Eric James | Adding reading of direct and diffuse irradiance and LAI 2024-02-20 | Jaymes Kenyon | Add calculation of PBLHGUST (from INITPOST.F) to support RRFS 10-m wind gust diagnostic 2024-03-15 | Wen Meng | Add option to read 3D soil-related variables 2024-03-25 | Eric James | Enabling reading of snow melt and surface albedo from RRFS 2024-04-03 | Eric James | Add reading of hourly averaged smoke and dust 2024-04-23 | Eric James | Updating smoke emissions to be 3D variable (ebu_smoke) 2024-05-01 | Eric James | set "prec_acc_dt1" as 15 min for RRFS 2024-05-09 | Eric James | Enable reading of clear-sky downwelling shortwave irradiance 2024-05-10 | Karina Asmar | Read omega from model output and calculate HGT for hydrostatic runs 2024-06-25 | Wen Meng | Add capability to read fhzero as either an integer or float
subroutine read_netcdf_2d_para (ncid, ista, ista_2l, iend, iend_2u, jsta, jsta_2l, jend, jend_2u, spval, varname, buf)
read_netcdf_2d_para() reads physics variables from UFS model output.
subroutine read_netcdf_3d_para (ncid, im, jm, ista, ista_2l, iend, iend_2u, jsta, jsta_2l, jend, jend_2u, spval, varname, buf, lm)
read_netcdf_3d_para() reads dynamics variables from UFS model output.
Detailed Description
initpost_netcdf() initializes post for run.
Author
Hui-Ya Chuang
Date
2016-03-04
This routine initializes constants and variables at the start of GFS model or post processor run.
Program History Log
Date Programmer Comments
2007-03-01 Hui-Ya Chuang Initial. Start from INITPOST_GFS_NEMS_MPIIO.f
2021-03-11 Bo Cui Change local arrays to dimension (im,jsta:jend)
2021-10-26 Jesse Meng 2D DECOMPOSITION
2022-02-07 Wen Meng Changes for parallel netcdf read
2022-03-15 Wen Meng Unify regional and global interfaces
2022-03-22 Wen Meng Read PWAT from model
2022-04-08 Bo Cui 2D decomposition for unified fv3 read interfaces
2022-06-05 Hui-Ya Chuang Modify dx/dy computation for RRFS domain over north pole
2022-07-10 Wen Meng Output lat/lon on four coner points of rotated lat-lon grids in text file.
2022-07-18 Wen Meng Read instant top of atmos ULWRF from model
2022-09-18 Li(Kate) Zhang Add aerosol fileds for GEFS-Aerosols (gocart_on) and UFS-Aerosols(nasa_on) model
2022-10-28 Eric James Modifications to allow passing through soil moisture availability field from RUC LSM for RRFS
2022-11-08 Kai Wang Read time averaged PM2.5 and O3 concentration from model
2022-11-08 Wen Meng Remove instant PM2.5 calculation
2022-11-16 Eric James Read smoke, dust, biomass burning, and hourly wildfire potential from RRFS
2022-12-07 Wen Meng Read AOD from AQM model
2022-12-23 Eric Aligo Read six winter weather diagnostics from model
2023-01-30 Sam Trahan Read cldfra or cldfra_bl, whichever is available
2023-02-23 Eric James Read coarse PM and aodtot from RRFS
2023-03-02 Sam Trahan Read lightning threat index fields
2023-03-22 WM Lewis Read RRFS effective radii (EFFRL, EFFRI, EFFRS)
2023-04-04 Li(Kate Zhang) Add namelist optoin for CCPP-Chem(UFS-Chem)
Definition in file INITPOST_NETCDF.f.
Function/Subroutine Documentation
initpost_netcdf()
subroutine initpost_netcdf (integer ncid2d, integer ncid3d)
2023-04-17 | Eric James | Read in unified ext550 extinction (and remove aodtot) for RRFS 2023-04-21 | Eric James | Read in / calculate some fields needed for GSL p-type diagnosis for RRFS 2023-05-31 | Wen Meng | Bug fix in qrmax initialization 2023-06-14 | Wen Meng | Bug fix of reading seaswtc and modification of sndepac calculation 2023-07-06 | Eric James | Read in SOILL on 9 levels for RRFS 2023-07-24 | Hui-Ya Chuang | Bug fix in tke inialization 2023-08-04 | Jaymes Kenyon | Read RRFS microphysics number concentrations (cloud water, cloud ice, rain) 2023-08-31 | Li(Kate Zhang)| Add condition to include/exclude processing nitrate from model output 2023-09-22 | Wen Meng | Bug fix in cwm initialization 2023-10-17 | Eric James | Including hail mixing ratio in calculation of hydrometeor VIL and cwm when present (NSSL microphysics) 2023-10-23 | Jaymes Kenyon | Read HAILCAST diagnostic output from RRFS 2024-01-12 | Wen Meng | Remove the hard-wired bucket for beyond F240 2024-02-07 | Eric James | Adding reading of direct and diffuse irradiance and LAI 2024-02-20 | Jaymes Kenyon | Add calculation of PBLHGUST (from INITPOST.F) to support RRFS 10-m wind gust diagnostic 2024-03-15 | Wen Meng | Add option to read 3D soil-related variables 2024-03-25 | Eric James | Enabling reading of snow melt and surface albedo from RRFS 2024-04-03 | Eric James | Add reading of hourly averaged smoke and dust 2024-04-23 | Eric James | Updating smoke emissions to be 3D variable (ebu_smoke) 2024-05-01 | Eric James | set "prec_acc_dt1" as 15 min for RRFS 2024-05-09 | Eric James | Enable reading of clear-sky downwelling shortwave irradiance 2024-05-10 | Karina Asmar | Read omega from model output and calculate HGT for hydrostatic runs 2024-06-25 | Wen Meng | Add capability to read fhzero as either an integer or float
Author
Hui-Ya Chuang
Date
2016-03-04
INITPOST_NETCDF() This routine initializes constants and variables at the start of GFS model or post processor run.
Parameters
[in] ncid2d integer netCDF ID of physics model output file.
[in] ncid3d integer netCDF ID of dynamics model output file.
Definition at line 68 of file INITPOST_NETCDF.f.
References exch(), msfps(), read_netcdf_2d_para(), and read_netcdf_3d_para().
Referenced by wrfpost().
read_netcdf_2d_para()
subroutine read_netcdf_2d_para (integer, intent(in) ncid, integer, intent(in) ista, integer, intent(in) ista_2l, integer, intent(in) iend, integer, intent(in) iend_2u, integer, intent(in) jsta, integer, intent(in) jsta_2l, integer, intent(in) jend, integer, intent(in) jend_2u, real, intent(in) spval, character(len=20), intent(in) varname, real, dimension(ista_2l:iend_2u,jsta_2l:jend_2u), intent(out) buf)
read_netcdf_2d_para() reads physics variables from UFS model output.
Parameters
[in] ncid integer netCDF ID.
[in] ista integer Start longitude latitude on a task subdomain.
[in] ista_2l integer Start longitude -2 of the subdomain.
[in] iend integer End longitude on a task subdomain.
[in] iend_2u integer End longitude +2 of the subdomain.
[in] jsta integer Start latitude on a task subdomain.
[in] jsta_2l integer Start latitude -2 of the subdomain.
[in] jend integer End latitude on a task subdomain.
[in] jend_2u integer End latitude +2 of the subdomain.
[in] spval real Missing value defined in UPP.
[in] varname character Variable name in netCDF file.
[out] buf real Variable values.
Definition at line 4096 of file INITPOST_NETCDF.f.
Referenced by initpost_netcdf().
read_netcdf_3d_para()
subroutine read_netcdf_3d_para (integer, intent(in) ncid, integer, intent(in) im, integer, intent(in) jm, integer, intent(in) ista, integer, intent(in) ista_2l, integer, intent(in) iend, integer, intent(in) iend_2u, integer, intent(in) jsta, integer, intent(in) jsta_2l, integer, intent(in) jend, integer, intent(in) jend_2u, real, intent(in) spval, character(len=20), intent(in) varname, real, dimension(ista_2l:iend_2u,jsta_2l:jend_2u,lm), intent(out) buf, integer, intent(in) lm)
read_netcdf_3d_para() reads dynamics variables from UFS model output.
Parameters
[in] ncid integer netCDF ID.
[in] im integer Full longitude domain.
[in] jm integer Full latitude domain.
[in] ista integer Start longitude latitude on a task subdomain.
[in] ista_2l integer Start longitude -2 of the subdomain.
[in] iend integer End longitude on a task subdomain.
[in] iend_2u integer End longitude +2 of the subdomain.
[in] jsta integer Start latitude on a task subdomain.
[in] jsta_2l integer Start latitude -2 of the subdomain.
[in] jend integer End latitude on a task subdomain.
[in] jend_2u integer End latitude +2 of the subdomain.
[in] spval real Missing value defined in UPP.
[in] varname character Variable name in netCDF file.
[out] buf real Variable values.
[in] lm integer Model levels.
Definition at line 4027 of file INITPOST_NETCDF.f.
Referenced by initpost_netcdf().