UPP: INITPOST.F File Reference
INITPOST.F File Reference
initpost() initializes post for run.
Functions/Subroutines
subroutine initpost
This routine initializes constants and variables at the start of an ETA model or post processor run.
Detailed Description
initpost() initializes post for run.
Author
Russ Treadon W/NP2
Date
1993-11-10
Definition in file INITPOST.F.
Function/Subroutine Documentation
initpost()
subroutine initpost
This routine initializes constants and variables at the start of an ETA model or post processor run.
This routine assumes that integers and reals are the same size.
Program History Log
Date Programmer Comments
1993-11-10 Russ Treadon Initial. Added DOCBLOC
1998-05-29 T Black Conversion from 1-D to 2-D
1999-01-20 Jim Tuccillo MPI Version
2001-10-25 H CHuang Modified to process hybrid model output
2002-06-19 Mike Baldwin WRF Version
2002-08-15 H CHuang Unit correction and generalize projection options
2021-03-11 Bo Cui Change local arrays to dimension (im,jsta:jend)
2023-01-24 Sam Trahan Comment-out wordy debug writes
Author
Russ Treadon W/NP2
Date
1993-11-10
Definition at line 25 of file INITPOST.F.
References collect_loc(), exch(), msfps(), and zensun().
Referenced by calrad_wcloud(), and wrfpost().