UPP: MDL2THANDPV.f File Reference
MDL2THANDPV.f File Reference
mdl2thandpv() vertical interpolation of model levels to isentropic and PV levels.
Functions/Subroutines
subroutine mdl2thandpv (kth, kpv, th, pv)
mdl2thandpv() vertical interpolation of model levels to isentropic and potential vorticity levels.
Detailed Description
mdl2thandpv() vertical interpolation of model levels to isentropic and PV levels.
For most applications this routine is the workhorse of the post processor. In a nutshell it interpolates data from model to THETA and PV surfaces.
Program History Log
Date Programmer Comments
2007-03-26 Chuang Initial
2011-02-06 J. Wang Add GRIB2 Option
2014-03-06 S. Moorthi Updated for threading and some optimization
2016-12-19 G.P. Lou Added A-grid regional models
2020-03-25 J Meng Remove grib1
2020-03-25 J Meng Remove grib1
2020-11-10 J Meng Use UPP_MATH and UPP_PHYSICS Modules
2021-03-11 B Cui Change local arrays to dimension (im,jsta:jend)
2021-10-26 J MENG 2D DECOMPOSITION
Author
Chuang W/NP22
Date
2007-03-26
Definition in file MDL2THANDPV.f.
Function/Subroutine Documentation
subroutine mdl2thandpv (integer, intent(in) kth, integer, intent(in) kpv, real, dimension(kth), intent(in) th, real, dimension(kpv), intent(in) pv)
mdl2thandpv() vertical interpolation of model levels to isentropic and potential vorticity levels.
Parameters
[in] kth integer Number of isentropic levels.
[in] kpv integer Number of potential vorticity levels.
[in] th real (kth) Isentropic levels (K).
[in] pv real (kpv) Potential vorticity (in PV units: 10**-6*K*m**2/kg/s).
Definition at line 30 of file MDL2THANDPV.f.
References upp_math::dvdxdudy(), upp_physics::fpvsnew(), upp_math::h2u(), p2pv(), p2th(), and pvetc().