UPP: MPI_FIRST.f File Reference
MPI_FIRST.f File Reference
SUBPROGRAM: MPI_FIRST SET UP MESSAGE PASSING INFO PRGRMMR: TUCCILLO ORG: IBM.
Functions/Subroutines
subroutine fullpole (a, rpoles)
fullpole()
subroutine mpi_first ()
MPI_FIRST() Sets up message passing info (MPI).
Detailed Description
SUBPROGRAM: MPI_FIRST SET UP MESSAGE PASSING INFO PRGRMMR: TUCCILLO ORG: IBM.
ABSTRACT: SETS UP MESSAGE PASSING INFO
Date Programmer Comments
2014-12-01 WM LEWIS ADDED ADDNL VARIABLES FOR SAT OUTPUT
2000-01-06 TUCCILLO ORIGINAL
2001-10-25 H CHUANG MODIFIED TO PROCESS HYBRID MODEL OUTPUT
2002-06-19 MIKE BALDWIN WRF VERSION
2011-12-16 SARAH LU MODIFIED TO INITIALIZE AEROSOL FIELDS
2012-01-07 SARAH LU MODIFIED TO INITIALIZE AIR DENSITY/LAYER THICKNESS
2021-07-07 JESSE MENG 2D DECOMPOSITION
2022-09-22 Li(Kate) Zhang Add new aerosols fields for UFS-Aerosols
2023-03-22 WM LEWIS ADDED EFFRI, EFFRS, EFFRL
USAGE: CALL MPI_FIRST INPUT ARGUMENT LIST:
OUTPUT ARGUMENT LIST:
OUTPUT FILES: STDOUT - RUN TIME STANDARD OUT.
SUBPROGRAMS CALLED: PARA_RANGE UTILITIES: NONE LIBRARY: COMMON - CTLBLK.comm
ATTRIBUTES: LANGUAGE: FORTRAN MACHINE : IBM RS/6000 SP
Definition in file MPI_FIRST.f.
Function/Subroutine Documentation
fullpole()
subroutine fullpole (real, dimension (ista_2l:iend_2u,jsta_2l:jend_2u), intent(inout) a, real, dimension(im,2), intent(inout) rpoles)
fullpole()
Parameters
[in,out] a real
[in,out] rpoles real
Definition at line 390 of file MPI_FIRST.f.
References ctlblk_mod::ibcoords, ctlblk_mod::icoords, and ctlblk_mod::rbcoords.
Referenced by upp_physics::caldiv(), upp_physics::calvor(), and mdl2thandpv().
mpi_first()
subroutine mpi_first ()
MPI_FIRST() Sets up message passing info (MPI).
Definition at line 46 of file MPI_FIRST.f.
References ctlblk_mod::ibcoords, ctlblk_mod::icoords, ctlblk_mod::rbcoords, and ctlblk_mod::rcoords.
Referenced by wrfpost().