UPP: MSFPS.f File Reference
MSFPS.f File Reference
msfps() computes the map scale factor for a polar stereographic grid at a give latitude.
Functions/Subroutines
subroutine msfps (LAT, TRUELAT1, MSF)
msfps() computes the map scale factor for a polar stereographic grid at a give latitude.
Detailed Description
msfps() computes the map scale factor for a polar stereographic grid at a give latitude.
This subroutine computes the map scale factor for a polar stereographic grid at a give latitude.
Parameters
[in] LAT Latitude at which map factor is valid.
[in] TRUELAT1 TRUELAT 1.
[out] MSF Map scale factor.
Program History Log
Date Programmer Comments
2006-11-01 Rozumalski Swiped from WRF si package
Author
Rozumalski
Date
2006-11-01
Definition in file MSFPS.f.
Function/Subroutine Documentation
subroutine msfps (real, intent(in) LAT, real, intent(in) TRUELAT1, real, intent(out) MSF)
msfps() computes the map scale factor for a polar stereographic grid at a give latitude.
This subroutine computes the map scale factor for a polar stereographic grid at a give latitude.
Parameters
[in] LAT Latitude at which map factor is valid.
[in] TRUELAT1 TRUELAT 1.
[out] MSF Map scale factor.
Definition at line 26 of file MSFPS.f.
Referenced by initpost(), initpost_gfs_nems_mpiio(), and initpost_netcdf().