UPP: PARA_RANGE.f File Reference
PARA_RANGE.f File Reference
Subroutines in this file set up decomposition values for 1D and 2D decomposition.
Functions/Subroutines
subroutine para_range (n1, n2, nprocs, irank, ista, iend)
Sets up decomposition values.
Detailed Description
Subroutines in this file set up decomposition values for 1D and 2D decomposition.
Program History Log
Date Programmer Comments
2000-01-06 Jim Tuccillo Initial
Author
Jim Tuccillo IBM
Date
2000-01-06
Definition in file PARA_RANGE.f.
Function/Subroutine Documentation
para_range()
subroutine para_range (integer, intent(in) n1, integer, intent(in) n2, integer, intent(in) nprocs, integer, intent(in) irank, integer, intent(out) ista, integer, intent(out) iend)
Sets up decomposition values.
Parameters
[in] N1 First interate value.
[in] N2 Last interate value.
[in] NPROCS Number of MPI tasks.
[in] IRANK My taks ID.
[out] ISTA First loop value.
[out] IEND Last loop value.
Definition at line 20 of file PARA_RANGE.f.
References para_range().
Referenced by para_range(), and setup_servers().