UPP: PROCESS.f File Reference
PROCESS.f File Reference
process() is a driver for major post routines.
Functions/Subroutines
subroutine process (kth, kpv, th, pv, iostatusD3D)
process() is a driver for major post routines.
Detailed Description
process() is a driver for major post routines.
This routine calls the major post processor routines.
 These routines are
 MDLFLD  - Calculate NMC SLP, set below surface fields,
           and posts data on model surfaces.
 MDL2P   - Posts data on isobaric surfaces.
 SURFCE  - Posts sounding data  surface based fields,
           and static or fixed fields.
 CLDRAD  - Post sounding/cloud/radiation fields.
 MISCLN  - Post miscellaneous (special) fields.
 FIXED   - Post fixed fields.
Date Programmer Comments
1992-12-21 Russ Treadon Initial
1998-06-01 T Black Conversion from 1-D to 2-D
2000-01-05 Jim Tuccillo MPI Version
2001-10-25 H CHUANG Modified to process hybrid model output
2002-06-19 Mike Baldwin WRF Version
2011-02-04 Jun Wang Add grib2 option
2023-01-24 Sam Trahan run IFI and compute its runtime
2023-08-24 Yali Mao Remove running MDL2STD_P
Author
Russ Treadon W/NP2
Date
1992-12-21
Definition in file PROCESS.f.
Function/Subroutine Documentation
process()
subroutine process (integer, intent(in) kth, integer, intent(in) kpv, real, dimension(kth), intent(in) th, real, dimension(kpv), intent(in) pv, integer, intent(in) iostatusD3D)
process() is a driver for major post routines.
Parameters
[in] kth integer Number of isentropic levels.
[in] kpv integer Number of potential vorticity levels.
[in] th real Isentropic levels (K).
[in] pv real Potential vorticity (PV units).
[in] iostatusD3D integer No longer used/supported.
Definition at line 40 of file PROCESS.f.
References ctlblk_mod::calrad_wcloud_tim, cldrad(), ctlblk_mod::cldrad_tim, ctlblk_mod::eta2p_tim, ctlblk_mod::etafld2_tim, fixed(), ctlblk_mod::fixed_tim, mdl2agl(), ctlblk_mod::mdl2agl_tim, mdl2p(), mdl2sigma(), mdl2sigma2(), ctlblk_mod::mdl2sigma_tim, mdl2thandpv(), ctlblk_mod::mdl2thandpv_tim, mdlfld(), miscln(), ctlblk_mod::miscln_tim, ctlblk_mod::run_ifi_tim, surfce(), and ctlblk_mod::surfce2_tim.
Referenced by wrfpost().