UPP: SURFCE.f File Reference
SURFCE.f File Reference
This routine posts surface-based fields.
Functions/Subroutines
subroutine qpf_comp (igetfld, compfile, fcst)
qpf_comp() Read in QPF threshold for exceedance grid.
subroutine surfce
SURFCE posts surface-based fields.
Detailed Description
This routine posts surface-based fields.
Program history log:
Date Programmer Comments
1992-12-21 RUSS TREADON Initial
1994-08-04 MICHAEL BALDWIN ADDED OUTPUT OF SFC FLUXES OF SENS AND LATENT HEAT AND THETA AT Z0
1994-11-04 MICHAEL BALDWIN ADDED INSTANTANEOUS PRECIP TYPE
1996-03-19 MICHAEL BALDWIN CHANGE SOIL PARAMETERS
1996-09-25 MICHAEL BALDWIN ADDED SNOW RATIO FROM EXPLICIT SCHEME
1996-10-17 MICHAEL BALDWIN CHANGED SFCEVP,POTEVP TO ACCUM. TOOK OUT -PTRACE FOR ACSNOW,SSROFF,BGROFF.
1997-04-23 MICHAEL BALDWIN TOOK OUT -PTRACE FOR ALL PRECIP FIELDS
1998-06-12 T BLACK CONVERSION FROM 1-D TO 2-D
1998-07-17 MIKE BALDWIN REMOVED LABL84
1998-08-18 MIKE BALDWIN COMPUTE RH OVER ICE
1998-12-22 MIKE BALDWIN BACK OUT RH OVER ICE
2000-01-04 JIM TUCCILLO MPI VERSION
2001-10-22 H CHUANG MODIFIED TO PROCESS HYBRID MODEL OUTPUT
2002-06-11 MIKE BALDWIN WRF VERSION ASSUMING ALL ACCUM VARS HAVE BUCKETS THAT FILL FROM T=00H ON
2002-08-28 H CHUANG COMPUTE FIELDS AT SHELTER LEVELS FOR WRF
2004-12-09 H CHUANG ADD ADDITIONAL LSM FIELDS
2005-07-07 BINBIN ZHOU ADD RSM MODEL
2005-08-24 GEOFF MANIKIN ADDED DOMINANT PRECIP TYPE
2011-02-06 JUN WANG ADDED GRIB2 OPTION
2013-08-05 S Moorthi Eliminate unnecessary arrays (reduce memory) and some cosmetic changes
2014-02-26 S Moorthi threading datapd assignment
2014-11-26 S Moorthi cleanup and some bug fix (may be?)
2020-03-25 J MENG remove grib1
2020-05-20 J MENG CALRH unification with NAM scheme
2020-11-10 J MENG USE UPP_PHYSICS MODULE
2021-03-11 B Cui change local arrays to dimension (im,jsta:jend)
2021-04-01 J MENG COMPUTATION ON DEFINED POINTS ONLY
2021-07-26 W Meng Restrict computation from undefined grids
2021-10-31 J MENG 2D DECOMPOSITION
2022-02-01 E JAMES Cleaning up GRIB2 encoding for six variables that cause issues with newer wgrib2 builds in RRFS system.
2022-11-16 E JAMES Adding dust from RRFS
2022-12-23 E Aligo Read six winter weather diagnostics from model.
2023-01-24 Sam Trahan store hourly accumulated precip for IFI and bucket time
2023-02-11 W Meng Add fix of time accumulation in bucket graupel for FV3 based models
2023-02-23 E James Adding coarse PM from RRFS
2023-03-22 S Trahan Fixed out-of-bounds access calling BOUND with wrong array dimensions
2023-04-21 E James Enabling GSL precip type for RRFS
2023-05-19 E James Cleaning up GRIB2 encoding for 1-h max precip rate
2023-06-15 E James Correcting bug fix in GSL precip type for RRFS (use 1h pcp, not run total pcp)
2023-10-04 W Meng Fix mismatched IDs from 526-530
2023-10-05 E James Correcting bug fix in GSL precip type for RRFS (was using 1000x 1h pcp)
2024-01-23 E James Using consistent snow ratio SR from history files throughout GSL precip type diagnosis.
2024-01-30 A Jensen Comment out graupel precipitation warning.
2024-02-07 E James Enabling output of LAI and wilting point for RRFS.
2024-03-25 E James Enabling output of column integrated soil moisture.
2024-04-03 E James Enabling output of hourly average smoke PM2.5 and dust PM10
2024-04-23 E James Adding smoke emissions (ebb) from RRFS
2024-05-01 E James Adapt the BUCKET1 type fields (15-min acc) for use in RRFS
2024-05-24 E James Modify the run total acc precip fields for 15-min output
2024-06-11 E James Modifying RRFS hourly average smoke/dust fields to be PM2.5 and PM20
2024-08-26 K Asmar Modify max winds at 10m agl for UFS time buckets
Note
USAGE: CALL SURFCE
OUTPUT FILES: NONE
SUBPROGRAMS CALLED: UTILITIES:
BOUND - ENFORCE LOWER AND UPPER LIMITS ON ARRAY ELEMENTS.
DEWPOINT - COMPUTE DEWPOINT TEMPERATURE.
CALDRG - COMPUTE SURFACE LAYER DRAG COEFFICENT
CALTAU - COMPUTE SURFACE LAYER U AND V WIND STRESSES.
LIBRARY: COMMON -
CTLBLK
RQSTFLD
Definition in file SURFCE.f.
Function/Subroutine Documentation
qpf_comp()
subroutine qpf_comp (integer, intent(in) igetfld, character(len=256), intent(in) compfile, integer, intent(in) fcst)
qpf_comp() Read in QPF threshold for exceedance grid.
Calculate exceedance grid.
Parameters
[in] compfile character File name for reference grid.
[in] fcst integer Forecast length in hours.
[in] igetfld integer ID of grib2 field.
Definition at line 7024 of file SURFCE.f.
Referenced by surfce().
surfce()
subroutine surfce
SURFCE posts surface-based fields.
Definition at line 78 of file SURFCE.f.
References bound(), caldrg(), caltau(), calwxt_bourg_post(), dewpoint(), and qpf_comp().
Referenced by process().