UPP: UPP_PHYSICS.f File Reference
UPP_PHYSICS.f File Reference
upp_physics is a collection of UPP subroutines for physics variables calculation.
Functions/Subroutines
subroutine upp_physics::breadboard1_main (nswFileName, mf, f1, f2, f3, f4, f5, f6, p1, p2, p3)
breadboard1_main() Called by calslr_roebber(), the breadboard subroutines are an AI Machine Learning algorithm that uses a neural network method to predict the snow solid-to-liquid ratio (SLR)
subroutine, public upp_physics::calcape (ITYPE, DPBND, P1D, T1D, Q1D, L1D, CAPE, CINS, PPARC, ZEQL, THUND)
calcape() computes CAPE and CINS.
subroutine, public upp_physics::calcape2 (ITYPE, DPBND, P1D, T1D, Q1D, L1D, CAPE, CINS, LFC, ESRHL, ESRHH, DCAPE, DGLD, ESP)
calcape2() computes CAPE and CINS.
subroutine, public upp_physics::caldiv (UWND, VWND, DIV)
CALDIV computes divergence.
subroutine, public upp_physics::calgradps (PS, PSX, PSY)
CALGRADPS computes gradients of a scalar field PS or LNPS.
subroutine, public upp_physics::calrh (P1, T1, Q1, RH)
CALRH() computes relative humidity.
subroutine, public upp_physics::calrh_gfs (P1, T1, Q1, RH)
calrh_gfs() computes relative humidity.
subroutine, public upp_physics::calrh_gsd (P1, T1, Q1, RHB)
CALRH_GSD() Compute RH with the NOAA GSL (formerly NOAA GSD) algorithm used for RUC and Rapid Refresh.
subroutine, public upp_physics::calrh_nam (P1, T1, Q1, RH)
calrh_nam() computes relative humidity.
subroutine, public upp_physics::calrh_pw (RHPW)
CALRH_PW() algorithm used at GSL for RUC and Rapid Refresh.
subroutine, public upp_physics::calslr_roebber (tprs, rhprs, slr)
calslr_roebber() computes snow solid-liquid-ratio slr using the Roebber algorithm.
subroutine, public upp_physics::calslr_uutah (SLR)
calslr_uutah() computes snow solid-liquid-ratio slr using the Steenburgh algorithm.
subroutine, public upp_physics::calvor (UWND, VWND, ABSV)
CALVOR() computes absolute vorticity.
elemental real function, public upp_physics::fpvsnew (t)
elemental real function, public upp_physics::tvirtual (T, Q)
Detailed Description
upp_physics is a collection of UPP subroutines for physics variables calculation.
Author
Jesse Meng
Date
2020-05-20
calcape() computes CAPE/CINS and other storm related variables.
calcape2() computes additional storm related variables.
caldiv() computes divergence.
calgradps() computes gardients of a scalar field PS or LNPS.
calrh(), calrh_nam(), calrh_gfs(), calrh_gsd() compute RH using various algorithms.
The NAM v4.1.18 algorithm (calrh_nam()) is selected as default for NMMB and FV3GFS, FV3GEFS, and FV3R for the UPP 2020 unification.
calrh_pw() algorithm use at GSD for RUC and Rapid Refresh.
calslr_roebber() computes snow solid-liquid-ratio slr using the Roebber algorithm.
calslr_uutah() computes snow solid-liquid-ratio slr using the UUtah Steenburgh algorithm.
calvor() computes absolute vorticity.
fpvsnew() computes saturation vapor pressure.
tvirtual() computes virtual temperature.
Date Programmer Comments
2020-05-20 Jesse Meng Initial
2022-07-11 Jesse Meng CALSLR_ROEBBER
2023-02-14 Jesse Meng CALSLR_UUTAH
2023-03-22 Sam Trahan Fix out-of-bounds access by not calling BOUND
Author
Jesse Meng
Date
2020-05-20
Definition in file UPP_PHYSICS.f.
Function/Subroutine Documentation
breadboard1_main()
subroutine upp_physics::breadboard1_main (character*20 nswFileName, real mf, real f1, real f2, real f3, real f4, real f5, real f6, real p1, real p2, real p3)
breadboard1_main() Called by calslr_roebber(), the breadboard subroutines are an AI Machine Learning algorithm that uses a neural network method to predict the snow solid-to-liquid ratio (SLR)
Definition at line 3070 of file UPP_PHYSICS.f.
calcape()
subroutine, public upp_physics::calcape (integer, intent(in) ITYPE, real, intent(in) DPBND, real, dimension(ista:iend,jsta:jend), intent(in) P1D, real, dimension(ista:iend,jsta:jend), intent(in) T1D, real, dimension(ista:iend,jsta:jend), intent(inout) Q1D, integer, dimension(ista:iend,jsta:jend), intent(in) L1D, real, dimension(ista:iend,jsta:jend), intent(inout) CAPE, real, dimension(ista:iend,jsta:jend), intent(inout) CINS, real, dimension(ista:iend,jsta:jend), intent(inout) PPARC, real, dimension(ista:iend,jsta:jend), intent(inout) ZEQL, real, dimension(ista:iend,jsta:jend) THUND)
calcape() computes CAPE and CINS.
This routine computes CAPE and CINS given temperature, pressure, and specific humidty. In "storm and cloud dynamics" (1989, academic press) cotton and anthes define CAPE (equation 9.16, p501) as
             el
   cape =  sum g * ln(thetap/thetaa) dz
            lcl
Where,
 el    = equilibrium level,
lcl    = lifting condenstation level,
  g    = gravitational acceleration,
thetap = lifted parcel potential temperature,
thetaa = ambient potential temperature.
Note that the integrand ln(THETAP/THETAA) approximately
equals (THETAP-THETAA)/THETAA.  This ratio is often used
in the definition of CAPE/CINS.
Two types of CAPE/CINS can be computed by this routine.  The
summation process is the same For both cases.  What differs
is the definition of the parcel to lift.  FOR ITYPE=1 the
parcel with the warmest THETA-E in A DPBND pascal layer above
the model surface is lifted.  the arrays P1D, T1D, and Q1D
are not used.  For itype=2 the arrays P1D, T1D, and Q1D
define the parcel to lift in each column.  Both types of
CAPE/CINS may be computed in a single execution of the post
processor.
This algorithm proceeds as follows.
For each column,
   (1)  Initialize running CAPE and CINS SUM TO 0.0
   (2)  Compute temperature and pressure at the LCL using
        look up table (PTBL).  Use either parcel that gives
        max THETAE in lowest DPBND above ground (ITYPE=1)
        or given parcel from t1D,Q1D,...(ITYPE=2).
   (3)  Compute the temp of a parcel lifted from the LCL.
        We know that the parcel's
        equivalent potential temperature (THESP) remains
        constant through this process.  we can
        compute tpar using this knowledge using look
        up table (subroutine TTBLEX).
   (4)  Find the equilibrium level.  This is defined as the
        highest positively buoyant layer.
        (If there is no positively buoyant layer, CAPE/CINS
         will be zero)
   (5)  Compute CAPE/CINS.
        (A) Compute THETAP.  We know TPAR and P.
        (B) Compute THETAA.  We know T and P.
   (6)  Add G*(THETAP-THETAA)*DZ to the running CAPE or CINS sum.
        (A) If THETAP > THETAA, add to the CAPE sum.
        (B) If THETAP < THETAA, add to the CINS sum.
   (7)  Are we at equilibrium level?
        (A) If yes, stop the summation.
        (b) if no, contiunue the summation.
   (8)  Enforce limits on CAPE and CINS (i.e. no negative CAPE)
Parameters
[in] ITYPE INTEGER Flag specifying how parcel to lift is identified. See comments above.
[in] DPBND Depth over which one searches for most unstable parcel.
[in] P1D Array of pressure of parcels to lift.
[in] T1D Array of temperature of parcels to lift.
[in] Q1D Array of specific humidity of parcels to lift.
[in] L1D Array of model level of parcels to lift.
[out] CAPE Convective available potential energy (J/kg).
[out] CINS Convective inhibition (J/kg).
[out] PPARC Pressure level of parcel lifted when one searches over a particular depth to compute CAPE/CIN.
[in,out] ZEQL Equivalent level height.
THUND Thunder parameter.
Date Programmer Comments
1993-02-10 Russ Treadon Initial
1993-06-19 Russ Treadon Generalized routine to allow for type 2 CAPE/CINS calculations
1994-09-23 Mike Baldwin Modified to use look up tables instead of complicated equations
1994-10-13 Mike Baldwin Modified to continue CAPE/CINS calc up to at highest buoyant layer
1998-06-12 T Black Conversion from 1-D TO 2-D
1998-08-18 T Black Compute APE internally
2000-01-04 Jim Tuccillo MPI Version
2002-01-15 Mike Baldwin WRF Version
2003-08-24 G Manikin Added level of parcel being lifted as output from the routine and added the depth over which one searches for the most unstable parcel as input
2010-09-09 G Manikin Changed computation to use virtual temp added eq lvl hght and thunder parameter
2015-??-?? S Moorthi Optimization and threading
2021-07-28 W Meng Restrict computation from undefined grids
2021-09-01 E Colon Equivalent level height index for RTMA
Author
Russ Treadon W/NP2
Date
1993-02-10
Definition at line 564 of file UPP_PHYSICS.f.
calcape2()
subroutine, public upp_physics::calcape2 (integer, intent(in) ITYPE, real, intent(in) DPBND, real, dimension(ista:iend,jsta:jend), intent(in) P1D, real, dimension(ista:iend,jsta:jend), intent(in) T1D, real, dimension(ista:iend,jsta:jend), intent(inout) Q1D, integer, dimension(ista:iend,jsta:jend), intent(in) L1D, real, dimension(ista:iend,jsta:jend), intent(inout) CAPE, real, dimension(ista:iend,jsta:jend), intent(inout) CINS, real, dimension(ista:iend,jsta:jend), intent(inout) LFC, real, dimension(ista:iend,jsta:jend), intent(inout) ESRHL, real, dimension(ista:iend,jsta:jend), intent(inout) ESRHH, real, dimension(ista:iend,jsta:jend), intent(inout) DCAPE, real, dimension(ista:iend,jsta:jend), intent(inout) DGLD, real, dimension(ista:iend,jsta:jend), intent(inout) ESP)
calcape2() computes CAPE and CINS.
This routine computes CAPE and CINS given temperature, pressure, and specific humidty. In "storm and cloud dynamics" (1989, academic press) cotton and anthes define CAPE (equation 9.16, p501) as
             el
   cape =  sum g * ln(thetap/thetaa) dz
            lcl
Where,
 el    = equilibrium level,
lcl    = lifting condenstation level,
  g    = gravitational acceleration,
thetap = lifted parcel potential temperature,
thetaa = ambient potential temperature.
Note that the integrand ln(THETAP/THETAA) approximately
equals (THETAP-THETAA)/THETAA.  This ratio is often used
in the definition of CAPE/CINS.
Two types of CAPE/CINS can be computed by this routine.  The
summation process is the same For both cases.  What differs
is the definition of the parcel to lift.  FOR ITYPE=1 the
parcel with the warmest THETA-E in A DPBND pascal layer above
the model surface is lifted.  the arrays P1D, T1D, and Q1D
are not used.  For itype=2 the arrays P1D, T1D, and Q1D
define the parcel to lift in each column.  Both types of
CAPE/CINS may be computed in a single execution of the post
processor.
This algorithm proceeds as follows.
For each column,
   (1)  Initialize running CAPE and CINS SUM TO 0.0
   (2)  Compute temperature and pressure at the LCL using
        look up table (PTBL).  Use either parcel that gives
        max THETAE in lowest DPBND above ground (ITYPE=1)
        or given parcel from t1D,Q1D,...(ITYPE=2).
   (3)  Compute the temp of a parcel lifted from the LCL.
        We know that the parcel's
        equivalent potential temperature (THESP) remains
        constant through this process.  we can
        compute tpar using this knowledge using look
        up table (subroutine TTBLEX).
   (4)  Find the equilibrium level.  This is defined as the
        highest positively buoyant layer.
        (If there is no positively buoyant layer, CAPE/CINS
         will be zero)
   (5)  Compute CAPE/CINS.
        (A) Compute THETAP.  We know TPAR and P.
        (B) Compute THETAA.  We know T and P.
   (6)  Add G*(THETAP-THETAA)*DZ to the running CAPE or CINS sum.
        (A) If THETAP > THETAA, add to the CAPE sum.
        (B) If THETAP < THETAA, add to the CINS sum.
   (7)  Are we at equilibrium level?
        (A) If yes, stop the summation.
        (b) if no, contiunue the summation.
   (8)  Enforce limits on CAPE and CINS (i.e. no negative CAPE)
Parameters
[in] ITYPE INTEGER Flag specifying how parcel to lift is identified. See comments above.
[in] DPBND Depth over which one searches for most unstable parcel.
[in] P1D Array of pressure of parcels to lift.
[in] T1D Array of temperature of parcels to lift.
[in] Q1D Array of specific humidity of parcels to lift.
[in] L1D Array of model level of parcels to lift.
[out] CAPE Convective available potential energy (J/kg).
[out] CINS Convective inhibition (J/kg).
[out] LFC level of free convection (m).
[out] ESRHL Lower bound to account for effective helicity calculation.
[out] ESRHH Upper bound to account for effective helicity calculation.
[out] DCAPE downdraft CAPE (J/KG).
[out] DGLD Dendritic growth layer depth (m).
[out] ESP Enhanced stretching potential.
Date Programmer Comments
1993-02-10 Russ Treadon Initial
1993-06-19 Russ Treadon Generalized routine to allow for type 2 CAPE/CINS calculations
1994-09-23 Mike Baldwin Modified to use look up tables instead of complicated equations
1994-10-13 Mike Baldwin Modified to continue CAPE/CINS calc up to at highest buoyant layer
1998-06-12 T Black Conversion from 1-D TO 2-D
1998-08-18 T Black Compute APE internally
2000-01-04 Jim Tuccillo MPI Version
2002-01-15 Mike Baldwin WRF Version
2003-08-24 G Manikin Added level of parcel being lifted as output from the routine and added the depth over which one searches for the most unstable parcel as input
2010-09-09 G Manikin Changed computation to use virtual temp added eq lvl hght and thunder parameter
2015-??-?? S Moorthi Optimization and threading
2021-09-03 J Meng Modified to add 0-3km CAPE/CINS, LFC, effective helicity, downdraft CAPE, dendritic growth layer depth, ESP
2021-09-01 E Colon Equivalent level height index for RTMA
2022-08-27 S Trahan Fixed bug in CALCAPE2 where extreme atmospheric conditions cause an out-of-bounds access
2022-09-01 S Trahan Fixed another bug in CALCAPE2 where extreme atmospheric conditions cause an out-of-bounds access
Author
Russ Treadon W/NP2
Date
1993-02-10
Definition at line 1043 of file UPP_PHYSICS.f.
References exch().
caldiv()
subroutine, public upp_physics::caldiv (real, dimension(ista_2l:iend_2u,jsta_2l:jend_2u,lm), intent(in) UWND, real, dimension(ista_2l:iend_2u,jsta_2l:jend_2u,lm), intent(in) VWND, real, dimension(ista:iend,jsta:jend,lm), intent(inout) DIV)
CALDIV computes divergence.
For GFS, this routine copmutes the horizontal divergence using 2nd-order centered scheme on a lat-lon grid
Parameters
[in] UWND U wind (m/s) mass-points.
[in] VWND V wind (m/s) mass-points.
[out] DIV divergence (1/s) mass-points.
Date Programmer Comments
2016-05-05 Sajal Kar Modified CALVORT to compute divergence from wind components
2016-07-22 S Moorthi Modified polar divergence calculation
Author
Sajal Kar W/NP2
Date
2016-05-05 caldiv() computes divergence.
Definition at line 2169 of file UPP_PHYSICS.f.
References exch(), and fullpole().
calgradps()
subroutine, public upp_physics::calgradps (real, dimension(ista_2l:iend_2u,jsta_2l:jend_2u), intent(in) PS, real, dimension(ista_2l:iend_2u,jsta_2l:jend_2u), intent(inout) PSX, real, dimension(ista_2l:iend_2u,jsta_2l:jend_2u), intent(inout) PSY)
CALGRADPS computes gradients of a scalar field PS or LNPS.
For GFS, this routine computes horizontal gradients of PS or LNPS. Using 2nd-order centered scheme on a lat-lon grid.
Parameters
[in] PS Surface pressure (Pa) mass-points.
[out] PSX Zonal gradient of PS at mass-points.
[out] PSY Meridional gradient of PS at mass-points.
Date Programmer Comments
2016-05-05 Sajal Kar Reduced from CALVORT to zonal and meridional gradients of given surface pressure PS, or LNPS
Author
Sajal Kar W/NP2
Date
2016-05-05
Definition at line 2447 of file UPP_PHYSICS.f.
References exch().
calrh()
subroutine, public upp_physics::calrh (real, dimension(ista:iend,jsta:jend), intent(in) P1, real, dimension(ista:iend,jsta:jend), intent(in) T1, real, dimension(ista:iend,jsta:jend), intent(inout) Q1, real, dimension(ista:iend,jsta:jend), intent(out) RH)
CALRH() computes relative humidity.
Parameters
[in] P1 real Pressure (Pa)
[in] T1 real Temperature (K)
[in,out] Q1 real Specific humidity (kg/kg)
Note
P1/T1/Q1 refer to pressure/temperature/specific humidity at the selected /requested level. For example, if the user wants relative humidity at 500mb, then T/P/Q at 500mb is input into the call to output RH@500mb
Parameters
[out] RH real Relative humidity (decimal form)
Definition at line 73 of file UPP_PHYSICS.f.
calrh_gfs()
subroutine, public upp_physics::calrh_gfs (real, dimension(ista:iend,jsta:jend), intent(in) P1, real, dimension(ista:iend,jsta:jend), intent(in) T1, real, dimension(ista:iend,jsta:jend), intent(inout) Q1, real, dimension(ista:iend,jsta:jend), intent(inout) RH)
calrh_gfs() computes relative humidity.
This routine computes relative humidity given pressure, temperature, specific humidity. an upper and lower bound of 100 and 1 percent relative humidity is enforced. When these bounds are applied the passed specific humidity array is adjusted as necessary to produce the set relative humidity.
Parameters
[in] P1 Pressure (pa)
[in] T1 Temperature (K)
[in,out] Q1 Specific humidity (kg/kg)
[out] RH Relative humidity (decimal form)
Date Programmer Comments
????-??-?? DENNIS DEAVEN Initial
1992-12-22 Russ Treadon Modified as described above
1998-06-08 T Black Conversion from 1-D to 2-D
1998-08-18 Mike Baldwin Modify to compute RH over ice as in model
1998-12-16 Geoff Manikin undo RH computation over ice
2000-01-04 Jim Tuccillo MPI Version
2002-06-11 Mike Baldwin WRF Version
2013-08-13 S. Moorthi Threading
2006-03-19 Wen Meng Modify top pressure to 1 pa
Author
Russ Treadon W/NP2
Date
1992-12-22
Definition at line 198 of file UPP_PHYSICS.f.
calrh_gsd()
subroutine, public upp_physics::calrh_gsd (real, dimension(ista:iend,jsta:jend) P1, real, dimension(ista:iend,jsta:jend) T1, real, dimension(ista:iend,jsta:jend) Q1, real, dimension(ista:iend,jsta:jend) RHB)
CALRH_GSD() Compute RH with the NOAA GSL (formerly NOAA GSD) algorithm used for RUC and Rapid Refresh.
Parameters
P1 real Pressure (Pa)
T1 real Temperature (K)
Q1 real Specific humidity (kg/kg)
Note
P1/T1/Q1 refer to pressure/temperature/specific humidity at the selected /requested level. For example, if the user wants relative humidity at 500mb, then T/P/Q at 500mb is input into the call to output RH@500mb
Parameters
RHB real Relative humidity (decimal form)
Definition at line 271 of file UPP_PHYSICS.f.
calrh_nam()
subroutine, public upp_physics::calrh_nam (real, dimension(ista:iend,jsta:jend), intent(in) P1, real, dimension(ista:iend,jsta:jend), intent(in) T1, real, dimension(ista:iend,jsta:jend), intent(inout) Q1, real, dimension(ista:iend,jsta:jend), intent(out) RH)
calrh_nam() computes relative humidity.
This routine computes relative humidity given pressure, temperature, specific humidity. an upper and lower bound of 100 and 1 percent relative humidity is enforced. When these bounds are applied the passed specific humidity array is adjusted as necessary to produce the set relative humidity.
Parameters
[in] P1 Pressure (pa)
[in] T1 Temperature (K)
[in,out] Q1 Specific humidity (kg/kg)
[out] RH Relative humidity (decimal form)
Date Programmer Comments
????-??-?? DENNIS DEAVEN Initial
1992-12-22 Russ Treadon Modified as described above
1998-06-08 T Black Conversion from 1-D to 2-D
1998-08-18 Mike Baldwin Modify to compute RH over ice as in model
1998-12-16 Geoff Manikin undo RH computation over ice
2000-01-04 Jim Tuccillo MPI Version
2002-06-11 Mike Baldwin WRF Version
2006-03-19 Wen Meng Modify top pressure to 1 pa
Author
Russ Treadon W/NP2
Date
1992-12-22
Definition at line 119 of file UPP_PHYSICS.f.
calrh_pw()
subroutine, public upp_physics::calrh_pw (real, dimension(ista:iend,jsta:jend) RHPW)
CALRH_PW() algorithm used at GSL for RUC and Rapid Refresh.
Parameters
RHPW real Relative humidity with respect to precipitable water (entire atmosphere)
Definition at line 313 of file UPP_PHYSICS.f.
calslr_roebber()
subroutine, public upp_physics::calslr_roebber (real, dimension(ista_2l:iend_2u,jsta_2l:jend_2u,lsm), intent(in) tprs, real, dimension(ista_2l:iend_2u,jsta_2l:jend_2u,lsm), intent(in) rhprs, real, dimension(ista_2l:iend_2u,jsta_2l:jend_2u), intent(out) slr)
calslr_roebber() computes snow solid-liquid-ratio slr using the Roebber algorithm.
Obtained the code and data from WPC. WPC's SLR products include SLR computed from GFS and NAM, SLR climotology, and averaged SLR. UPP computes SLR for GFS and RRFS. SLR climatology is not used in UPP calculation but the data is saved in fix directory for reference. Breadboard coefficients are included in this module to enhance the performance. Original Breadboard coefficients files are also saved in fix directory.
Parameters
[in] tprs real Temperature on pressure levels.
[in] rhprs real Relative humidity on pressure levels.
[out] slr real Solid snow to liquid ratio.
Date Programmer Comments
2022-07-11 Jesse Meng Initial
2023-01-06 | Jesse Meng ! Import Breadboard coefficients into module
Author
Jesse Meng
Date
2022-07-11
Definition at line 2682 of file UPP_PHYSICS.f.
calslr_uutah()
subroutine, public upp_physics::calslr_uutah (real, dimension(ista_2l:iend_2u,jsta_2l:jend_2u), intent(out) SLR)
calslr_uutah() computes snow solid-liquid-ratio slr using the Steenburgh algorithm.
Obtained the code and data from U of Utah Jim Steenburgh and Peter Veals. SLR = m1X1 + m2X2 + m3X3 + m4X4 + m5X5 + m6X6 + b.
 X1 = wind speed at at 1km above ground level (AGL) in m/s
 m1 = -0.174848
 X2 = temperature at 2km AGL in Kelvin
 m2 = -0.52644
 X3 = wind speed at 2 km AGL in m/s
 m3 = 0.034911
 X4 = wind speed at 500 m AGL in m/s
 m4 = -0.270473
 X5 = temperature at 1 km AGL in Kelvin
 m5 = 0.028299
 X6 = temperature at 500 m AGL in m/s
 m6 = 0.096273
 b =  118.35844
Parameters
[out] SLR real Solid snow to liquid ratio
Date Programmer Comments
2023-01-23 Jesse Meng Initial
Author
Jesse Meng
Date
2023-01-03
Definition at line 4351 of file UPP_PHYSICS.f.
calvor()
subroutine, public upp_physics::calvor (real, dimension(ista_2l:iend_2u,jsta_2l:jend_2u), intent(in) UWND, real, dimension(ista_2l:iend_2u,jsta_2l:jend_2u), intent(in) VWND, real, dimension(ista_2l:iend_2u,jsta_2l:jend_2u), intent(inout) ABSV)
CALVOR() computes absolute vorticity.
Parameters
[in] UWND U wind (m/s) mass-points.
[in] VWND V wind (m/s) mass-points.
[out] ABSV absolute vorticity (1/s) mass-points.
Date Programmer Comments
1992-12-22 Russ Treadon Initial
1998-06-08 T Black Convesion from 1-D to 2-D
2000-01-04 Jim Tuccillo MPI Version
2002-01-15 Mike Baldwin WRF Version C-grid
2005-03-01 H Chuang Add NMM E grid
2005-05-17 H Chuang Add Potential vorticity calculation
2005-07-07 B Zhou Add RSM in computing DVDX, DUDY and UAVG
2013-08-09 S Moorthi Optimize the vorticity loop including threading
2016-08-05 S Moorthi add zonal filetering
2019-10-17 Y Mao Skip calculation when U/V is SPVAL
2020-11-06 J Meng Use UPP_MATH Module
2022-05-26 H Chuang Use GSL approach for FV3R
Author
Russ Treadon W/NP2
Date
1992-12-22
Definition at line 1745 of file UPP_PHYSICS.f.
References exch(), and fullpole().
fpvsnew()
elemental real function, public upp_physics::fpvsnew (real, intent(in) t)
fpvsnew() computes saturation vapor pressure.
Compute saturation vapor pressure from the temperature. A linear interpolation is done between values in a lookup table computed in gpvs. See documentation for fpvsx for details. Input values outside table range are reset to table extrema. The interpolation accuracy is almost 6 decimal places. On the Cray, fpvs is about 4 times faster than exact calculation. This function should be expanded inline in the calling routine.
Parameters
[in] t Real(krealfp) Temperature in Kelvin.
Returns
fpvsnew Real(krealfp) Saturation vapor pressure in Pascals.
Date Programmer Comments
1991-05-07 Iredell Initial. Made into inlinable function
1994-12-30 Iredell Expand table
1999-03-01 Iredell F90 module
2001-02-26 Iredell Ice phase
Author
N Phillips w/NMC2X2
Date
1982-12-30
Definition at line 379 of file UPP_PHYSICS.f.
tvirtual()
elemental real function, public upp_physics::tvirtual (real, intent(in) T, real, intent(in) Q)
Returns
TVIRTUAL() Computes virtual temperature
Parameters
[in] T real Temperature
[in] Q real Specific humidity
Returns
virtual temperature
Definition at line 1703 of file UPP_PHYSICS.f.