UPP: UPP_MATH.f File Reference
UPP_MATH.f File Reference
upp_math is a collection of UPP subroutines for numerical math functions calculation.
Functions/Subroutines
subroutine, public upp_math::dvdxdudy (uwnd, vwnd)
dvdxdudy() computes dudy, dvdx, uwnd
subroutine, public upp_math::h2u (ingrid, outgrid)
subroutine, public upp_math::h2v (ingrid, outgrid)
subroutine, public upp_math::u2h (ingrid, outgrid)
subroutine, public upp_math::v2h (ingrid, outgrid)
Variables
real, dimension(:,:), allocatable, public upp_math::ddudy
DDUDY du/dy derivative.
real, dimension(:,:), allocatable, public upp_math::ddvdx
DDVDX dv/dx derivative.
real, dimension(:,:), allocatable, public upp_math::uuavg
UUAVG u wind velocity on mass points.
Detailed Description
upp_math is a collection of UPP subroutines for numerical math functions calculation.
Author
Jesse Meng
Date
2020-05-20
dvdxdudy() computes dudy, dvdx, uwnd
h2u(), h2v(), u2h(), v2h() interpolate variables between U, V, H, points adopted from UPP subroutine GRIDAVG.f
Program history log:
Date Programmer Comments
2020-05-20 Jesse Meng Initial
2022-06-10 Wen Meng Modify dvdxdudy to retrict computation on undefined grids
2023-03-03 Sam Trahan Add some missing exchanges (grids that only need i-direction exchanges)
Author
Jesse Meng
Date
2020-05-20
Definition in file UPP_MATH.f.
Function/Subroutine Documentation
dvdxdudy()
subroutine, public upp_math::dvdxdudy (real, dimension(ista_2l:iend_2u,jsta_2l:jend_2u), intent(in) uwnd, real, dimension(ista_2l:iend_2u,jsta_2l:jend_2u), intent(in) vwnd)
dvdxdudy() computes dudy, dvdx, uwnd
Parameters
[in] uwnd real U horizontal wind component on velocity points
[in] vwnd real V horizontal wind component on velocity points
Definition at line 54 of file UPP_MATH.f.
h2u()
subroutine, public upp_math::h2u (real, dimension(ista_2l:iend_2u,jsta_2l:jend_2u), intent(in) ingrid, real, dimension(ista_2l:iend_2u,jsta_2l:jend_2u), intent(out) outgrid)
H2U() interpolates from H points onto U points
Parameters
[in] ingrid Input grid on H points
[out] outgrid Output grid on U points
Author: CHUANG, EMC, Dec. 2010
Definition at line 137 of file UPP_MATH.f.
References exch().
h2v()
subroutine, public upp_math::h2v (real, dimension(ista_2l:iend_2u,jsta_2l:jend_2u), intent(in) ingrid, real, dimension(ista_2l:iend_2u,jsta_2l:jend_2u), intent(out) outgrid)
H2V() interpolates from H points onto V points
Parameters
[in] ingrid Input grid on H points.
[out] outgrid Output grid on V points.
Author: CHUANG, EMC, Dec. 2010
Definition at line 202 of file UPP_MATH.f.
References exch().
u2h()
subroutine, public upp_math::u2h (real, dimension(ista_2l:iend_2u,jsta_2l:jend_2u), intent(in) ingrid, real, dimension(ista_2l:iend_2u,jsta_2l:jend_2u), intent(out) outgrid)
U2H() interpolates from U points onto H points
Parameters
[in] ingrid Input grid on U points.
[out] outgrid Output grid on H points.
Author: CHUANG, EMC, Dec. 2010
Definition at line 255 of file UPP_MATH.f.
References exch().
v2h()
subroutine, public upp_math::v2h (real, dimension(ista_2l:iend_2u,jsta_2l:jend_2u), intent(in) ingrid, real, dimension(ista_2l:iend_2u,jsta_2l:jend_2u), intent(out) outgrid)
V2H() interpolates from V points onto H points
Parameters
[in] ingrid Input grid on V points.
[out] outgrid Output grid on H points.
Author: CHUANG, EMC, Dec. 2010
Definition at line 308 of file UPP_MATH.f.
References exch().
Variable Documentation
ddudy
real, dimension(:,:), allocatable, public upp_math::ddudy
DDUDY du/dy derivative.
Definition at line 38 of file UPP_MATH.f.
ddvdx
real, dimension(:,:), allocatable, public upp_math::ddvdx
DDVDX dv/dx derivative.
Definition at line 35 of file UPP_MATH.f.
uuavg
real, dimension(:,:), allocatable, public upp_math::uuavg
UUAVG u wind velocity on mass points.
Definition at line 41 of file UPP_MATH.f.