UPP: WRFPOST.F File Reference
WRFPOST.F File Reference
wrfpost() drives the external wrf post processor.
Functions/Subroutines
program wrfpost
Detailed Description
wrfpost() drives the external wrf post processor.
Returns
wrfpost
Program history log:
Date Programmer Comments
1992-12-24 Russ Treadon Coded etapost as stand alone code
1998-05-29 Black Conversion of post code from 1-D to 2-D
1900-02-04 Jim Tuccillo Parallel version via MPI
2001-02-15 Jim Tuccillo Many common blocks replaced with modules to support fortran "allocate"s for the exact size of the arrays needed based on the number of mpi tasks. This was done to reduce the address space that the loader sees. These changes were necessary for running larger domains such as 12 kms
2001-06-15 JIM Tuccillo Added asyncronous I/O capability. if there are more than one mpi task, the io will be done aynchronously by the last MPI task.
2002-06-17 Mike Baldwin Convert etapost to wrfpost. Include wrf I/O api for input of model data. Modify code to deal with C-grid data. Streamline output to a call of one subroutine instead of three. Replace common blocks with a limited number of modules.
2004-01-01 H Chuang Added nmm io module and binary options
2005-07-08 Binbin Zhou Added RSM model
2005-12-05 H Chuang Added capability to output off-hour forecast which has no impacts on on-hour forecast
2006-02-20 Chuang, Black, and Rogers Finalized complete list of NAM operational products from WRF
2006-02-27 H Chuang Modified to post multiple forecast hours in one execution
2006-03-03 H Chuang Added parrish's mpi binary io to read binary WRF file as random asscess so that variables in WRF output don't have to be read in in specific order
2011-02-06 J Wang Add grib2 option
2011-12-14 Sarah Lu Add the option to read ngac aer file
2012-01-28 J WANG Use post available fields in xml file for grib2
2013-06-25 S Moorthi Add gocart_on logical option to save memory
2013-10-03 J Wang Add option for po to be pascal, and add gocart_on,d3d_on and popascal to namelist
2020-03-25 J Meng Remove grib1
2021-06-20 W Meng Remove reading grib1 and gfsio lib
2021-07-07 J MENG 2D DECOMPOSITION
2021-10-22 KaYee Wong Created formal fortran namelist for itag
2021-11-03 Tracy Hertneky Removed SIGIO option
2022-01-14 W Meng Remove interfaces INITPOST_GS_NEMS, INITPOST_NEMS_MPIIO, INITPOST_NMM and INITPOST_GFS_NETCDF
2022-03-15 W Meng Unify FV3 based interfaces
2022-09-22 L Zhang Add option of nasa_on to process ufs-aerosols
2022-11-08 K Wang Replace aqfamaq_on with aqf_on
2023-01-24 Sam Trahan write_ifi_debug_files flag for IFI debug capability
2023-03-21 Jesse Meng Add slrutah_on option to use U Utah SLR
2023-04-04 Li(Kate Zhang) Add namelist optoin for CCPP-Chem (UFS-Chem) and 2D diag. output (d2d_chem) for GEFS-Aerosols and CCPP-Chem model.
2023-05-20 Rahul Mahajan Bug fix for fileNameFlat as namelist configurable
2023-08-16 Yali Mao Add gtg_on logical option
2023-11-29 Eric James Add method_blsn logical option
2024-08-19 Jaymes Kenyon Adding a call to INITPOST_MPAS
2024-08-30 Jaymes Kenyon Hard coding iSF_SURFACE_PHYSICS=3 when modelname=RAPR and submodelname=MPAS
Author
Mike Bladwin NSSL/SPC
Date
2002-06-18
Definition in file WRFPOST.F.
Function/Subroutine Documentation
wrfpost()
program wrfpost
Returns
wrfpost
Definition at line 46 of file WRFPOST.F.
References allocate_all(), ctlblk_mod::calrad_wcloud_tim, ctlblk_mod::cldrad_tim, de_allocate(), ctlblk_mod::eta2p_tim, ctlblk_mod::etafld2_tim, ctlblk_mod::fixed_tim, initpost(), initpost_gfs_nems_mpiio(), initpost_mpas(), initpost_nems(), initpost_netcdf(), ctlblk_mod::mdl2agl_tim, ctlblk_mod::mdl2sigma_tim, ctlblk_mod::mdl2std_tim, ctlblk_mod::mdl2thandpv_tim, ctlblk_mod::miscln_tim, mpi_first(), mpi_last(), process(), read_xml(), ctlblk_mod::readxml_tim, ctlblk_mod::run_ifi_tim, server(), set_outflds(), setup_servers(), ctlblk_mod::surfce2_tim, and ctlblk_mod::time_output.