#!/bin/sh

export PS4='$SECONDS + '

date
set -xa

#Specify whether the run is production or development
#
export RUN_ENVIR=${RUN_ENVIR:-prod}
export envir=${envir:-prod}

####################################
# Specify version numbers
####################################
export post_ver=${post_ver:-v5.0.0}
export gsm_ver=${gsm_ver:-v12.0.0}

####################################
# obtain unique process id (pid) and make temp directory
####################################
export pid=$$
export DATA_IN=${DATA_IN:-/tmpnwprd1}
export DATA=$DATA_IN/${job}.${pid}
mkdir $DATA
cd $DATA

####################################
# Specify NET and RUN Name and model
####################################
export NET=gfs
export RUN=gfs

####################################
# File To Log Msgs
####################################
export jlogfile=/com/logs/jlogfiles/jlogfile.${job}.${pid}

####################################
# Determine Job Output Name on System
####################################
export cyc=${cyc:-00}
export cycle=t${cyc}z
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

####################################
# SAVEGES  - Copy Files From TMPDIR to $GESdir
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
# RERUN    - Rerun posts from beginning (default no)
# VERBOSE  - Specify Verbose Output in global_postgp.sh
####################################
export SAVEGES=YES
export SENDECF=YES
export SENDCOM=YES
export SENDDBN=YES
export SENDDBN_GB2=YES
export RERUN=NO
export VERBOSE=YES

####################################
# Specify Execution Areas
####################################
export HOMEGLOBAL=${HOMEGLOBAL:-/nw${envir}}
export EXECGLOBAL=${EXECGLOBAL:-HOMEGLOBAL/exec}
export USHGLOBAL=${USHGLOBAL:-HOMEGLOBAL/ush}
export FIXGLOBAL=${FIXGLOBAL:-HOMEGLOBAL/fix}
export SCRGLOBAL=${SCRGLOBAL:-$HOMEGLOBAL/scripts}
export UTILGLOBAL=${UTILGLOBAL:-$HOMEGLOBAL/util}
export PARMGLOBAL=${PARMGLOBAL:-HOMEGLOBAL/parm}

export HOMEGSM=${HOMEGSM:-/nw${envir}/gsm.$gsm_ver}
export EXECGSM=${EXECGSM:-$HOMEGSM/exec}
export FIXGSM=${FIXGSM:-$HOMEGSM/fix/fix_am}
export USHGSM=${USHGSM:-$HOMEGSM/ush}
export SCRGSM=${SCRGSM:-$HOMEGSM/scripts}
export UTILGSM=${UTILGSM:-$HOMEGSM/util}
export PARMGSM=${PARMGSM:-$HOMEGSM/parm}

export HOMEPOST=${HOMEPOST:-/nw${envir}/ncep_post.$post_ver}
export EXECPOST=${EXECPOST:-$HOMEPOST/exec}
export FIXPOST=${FIXPOST:-$HOMEPOST/fix}
export USHPOST=${USHPOST:-$HOMEPOST/ush}
export SCRPOST=${SCRPOST:-$HOMEPOST/scripts}
export UTILPOST=${UTILPOST:-$HOMEPOST/util}
export PARMPOST=${PARMPOST:-$HOMEPOST/parm}

export HOMEUTIL=${HOMEUTIL:-/nw${envir}/util}
export EXECUTIL=${EXECUTIL:-$HOMEUTIL/exec}
export FIXUTIL=${FIXUTIL:-$HOMEUTIL/fix}

export ERRSCRIPT=err_chk
export LOGSCRIPT=startmsg
export REDOUT='1>>'
export REDERR='2>'

##############################
# Set up the UTILITIES
##############################
export utilscript=${utilscript:-$UTILGLOBAL/ush}
export utilexec=${utilexec:-$UTILGLOBAL/exec}
export GRBINDEX=${utilexec:-/nw${envir}/util/exec/grbindex}

##############################
# Run setup to initialize working directory and utility scripts
##############################
$utilscript/setup.sh

##############################
# Run setpdy and initialize PDY variables
##############################
#export PDY=20121022
$utilscript/setpdy.sh
. PDY

##############################################
# Define COM directories
##############################################
export COMIN=/com/${NET}/${envir}/${RUN}.${PDY}
export COMOUT=/com/${NET}/${envir}/${RUN}.${PDY}
mkdir -m 775 -p $COMOUT

##############################################
# Define GES directories
##############################################
gespath=/nwges/${envir}
export GESdir=$gespath/${RUN}.${PDY}
mkdir -m 775 -p $GESdir

####################################
# Specify Special Post Vars
####################################
export IGEN_ANL=81
export IGEN_FCST=96

export POSTGPVARS="KPO=47,PO=1000.,975.,950.,925.,900.,875.,850.,825.,800.,775.,750.,725.,700.,675.,650.,625.,600.,575.,550.,525.,500.,475.,450.,425.,400.,375.,350.,325.,300.,275.,250.,225.,200.,175.,150.,125.,100.,70.,50.,30.,20.,10.,7.,5.,3.,2.,1.,"

export CHGRESEXEC=${CHGRESEXEC:-$EXECGSM/global_chgres}
export CHGRESSH=${CHGRESSH:-$USHGSM/global_chgres.sh}
export CHGRESTHREAD=32
export OVERPARMEXEC=$EXECGLOBAL/overparm_grib
export POSTGPEXEC=${POSTGPEXEC:-$EXECPOST/ncep_post}

###############################
# Parameters for chgres to use
###############################
export LSOIL=4
export LATCH=8

#######################################################
# Define Variables for testing
# This is for the convenience of parallel testing
# Should be removed when moving to /nwprod
#######################################################
#FHOUR_HIGH=180

#if [ "$post_times" = "anl" ]
#then
#  export LEVS=64
#  export JCAP=382

#elif [ "$post_times" -le $FHOUR_HIGH ]
#then
#  export LEVS=64
#  export JCAP=382
#else
#  export LEVS=64
#  export JCAP=190
#fi

#######################################
# Specify Restart File Name to Key Off
#######################################
restart_file=$COMIN/${RUN}.t${cyc}z.logf

####################################
# Specify Timeout Behavior of Post
#
# SLEEP_TIME - Amount of time to wait for
#              a restart file before exiting
# SLEEP_INT  - Amount of time to wait between
#              checking for restart files
####################################
export SLEEP_TIME=900
export SLEEP_INT=5

env

#############################################################
# Execute the regular master ncep post script
$SCRPOST/exgfs_nceppost.sh.ecf
#############################################################

if [ $post_times -eq 84  ]
then
    echo "`hostname`  --  `date`" > $COMOUT/where_ibm_${RUN}_post84_ran.${cycle}
fi

##############################
# Remove the Temporary working directory
##############################
cd /tmpnwprd
rm -rf $DATA

date


