################################################################################
# This makefile was produced by fmjif at 17:21:11 on 97/02/24.
SHELL=	/bin/sh
CMD=	copygb
FOPTS=	-O3   -qrealsize=8 -qnosave
LOPTS=	-qsmp=noauto     -lessl
INCS=	
OBJS=	copygb.o
LIBS= /global/save/wx20gg/bgrids/w3mods/w3/lib/libw3_d.a \
      /global/save/wx20gg/bgrids/ipmods/libip_d.a \
      -L/nwprod/lib -lbacio_4 -lsp_d	
################################################################################
$(CMD):	$(OBJS)
	ncepxlf $(LOPTS) $(OBJS) $(LIBS) -o $(CMD)
$(OBJS):	$(INCS)
copygb.o:	copygb.f
	ncepxlf -c $(FOPTS) $*.f
clean:	
	-rm -f $(OBJS)
