UPP: BOUND.f File Reference
BOUND.f File Reference
bound() clips data in passed array.
Functions/Subroutines
subroutine bound (fld, fmin, fmax)
This routine bounds data in the passed array FLD (im x jm elements long) and clips data values such that on exiting the routine.
Detailed Description
bound() clips data in passed array.
Author
Russ Treadon W/NP2
Date
1993-01-18
Definition in file BOUND.f.
Function/Subroutine Documentation
bound()
subroutine bound (real, dimension(im,jm), intent(inout) fld, real, intent(in) fmin, real, intent(in) fmax)
This routine bounds data in the passed array FLD (im x jm elements long) and clips data values such that on exiting the routine.
fmin <= fld(i,j) <= fmax
for all points.
Parameters
[in] FMIN Lower (inclusive) bound for data.
[in] FMAX Upper (inclusive) bound for data.
[out] FLD Array whose elements are bounded by [FMIN,FMAX].
Program History Log
Date Programmer Comments
1993-01-18 Russ Treadon Initial
1993-05-07 Russ Treadon Added DOCBLOC
1998-05-29 T Black Conversion from 1-D to 2-D
2000-01-04 Jim Tuccillo MPI Version
2002-04-24 Mike Baldwin WRF Version
2021-09002 Bo Cui Decompose UPP in X direction
Author
Russ Treadon W/NP2
Date
1993-01-18
Definition at line 29 of file BOUND.f.
Referenced by mdl2sigma(), mdlfld(), miscln(), and surfce().