UPP: MDL2STD_P.f File Reference
MDL2STD_P.f File Reference
mdl2std_p() vertical interpolation of model levels to standard atmospheric pressure.
Functions/Subroutines
subroutine mdl2std_p ()
mdl2std_p() vertical interpolation of model levels to standard atmospheric pressure.
real function p2h (p)
P2H() converts pressure levels (hPa) to geopotential heights.
real function relabel (p)
relabel() relabels the pressure level to reference (or standard atmospheric) pressure levels rather than model pressure.
Detailed Description
mdl2std_p() vertical interpolation of model levels to standard atmospheric pressure.
Originated from MISCLN.f. This routine interpolate to standard atmospheric pressure, instead of model pressure.
Program History Log
Date Programmer Comments
2019-09-24 Y Mao Rewritten from MISCLN.f
2020-05-20 J Meng CALRH unification with NAM scheme
2020-11-10 J Meng Use UPP_PHYSICS Module
2021-03-11 B Cui Change local arrays to dimension (im,jsta:jend)
2021-10-14 J MENG 2D DECOMPOSITION
2022-05-25 Y Mao Remove interpolation of VVEL/ABSV/CLWMR
2023-03-14 Y Mao Remove interpolation of RH, remove use CALRH and CALVOR
Author
Y Mao W/NP22
Date
2019-09-24
Definition in file MDL2STD_P.f.
Function/Subroutine Documentation
mdl2std_p()
subroutine mdl2std_p
mdl2std_p() vertical interpolation of model levels to standard atmospheric pressure.
Definition at line 22 of file MDL2STD_P.f.
References fdlvl_mass(), fdlvl_uv(), p2h(), and relabel().
p2h()
real function p2h (real, intent(in) p)
P2H() converts pressure levels (hPa) to geopotential heights.
Uses ICAO standard atmosphere parameters as defined here: https://www.nen.nl/pdfpreview/preview_29424.pdf
Parameters
[in] p real Pressure (hPa)
Returns
P2H Geopotential height.
Definition at line 399 of file MDL2STD_P.f.
References p2h().
Referenced by mdl2std_p(), and p2h().
relabel()
real function relabel (real, intent(in) p)
relabel() relabels the pressure level to reference (or standard atmospheric) pressure levels rather than model pressure.
Parameters
[in] p real Pressure (Pa).
Returns
relabel Relabeled pressure value in reference (standard atmospheric) pressure levels.
Definition at line 423 of file MDL2STD_P.f.
References relabel().
Referenced by mdl2std_p(), and relabel().