UPP: MDLFLD.f File Reference
MDLFLD.f File Reference
Functions/Subroutines
subroutine mdlfld
SUBPROGRAM: MDLFLD SLP AND NATIVE LEVEL POSTING PRGRMMR: TREADON ORG: W/NP2 DATE: 92-12-21
Function/Subroutine Documentation
mdlfld()
subroutine mdlfld
SUBPROGRAM: MDLFLD SLP AND NATIVE LEVEL POSTING PRGRMMR: TREADON ORG: W/NP2 DATE: 92-12-21
ABSTRACT: THIS ROUTINE DOES SEVERAL THINGS. IT IS THE FIRST ROUTINE CALLED BY POST PROCESSOR SUBROUTINE PROCESS WHICH SETS THE ORDER IN WHICH FIELDS ARE POSTED. THE NEGATIVE SPECIFIC HUMIDITY IS CLIPPED. COMPUTE THE STANDARD NMC SEA LEVEL PRESSURE IF THIS OPTION IS ACTIVATED. FINALLY WE COMPUTE/POST REQUESTED FIELDS ON MODEL LAYERS.
PROGRAM HISTORY LOG: 92-12-21 RUSS TREADON 93-09-01 RUSS TREADON - ADDED ADDITIONAL OUTPUT FIELDS. 96-03-20 MIKE BALDWIN - ADDED CLOUD TOP TEMPS, CHANGE CLOUD WATER TO CONTAIN WATER ONLY 97-04-29 GEOFF MANIKIN - MOVED CLOUD TOP TEMPS TO CLDRAD 98-06-01 T BLACK - CONVERSION FROM 1-D TO 2-D 98-07-20 MIKE BALDWIN - REMOVED LABL84 98-08-18 T BLACK - REMOVED EXCESS SPACE IN EXTRA.com 00-01-04 JIM TUCCILLO - MPI VERSION 01-10-22 H CHUANG - MODIFIED TO PROCESS HYBRID MODEL OUTPUT 02-01-15 MIKE BALDWIN - WRF VERSION 04-11-17 H CHUANG, B FERRIER, AND Y JIN - ADD HYDROMETEORS, VISIBILITY & RADAR REFLECTIVITY 05-07-07 B ZHOU ADD RSM MODEL A GRID
05-08-18 B ZHOU ADD /VISB/ COMMON BLOCK TO PASS VISIBILITY TO AVIATION SUBROUTINE TO CALCULATE FLIGHT CONDITION RESTRICTION 11-02-06 J Wang - add grib2 option 12-01-06 S LU - MODIFIED TO PROCESS GOCART OUTPUT 12-01-21 S LU - MODIFIED TO PROCESS NON-DUST AEROSOLS 14-02-27 S MOORTHI - Added threading and some cleanup 14-11-17 B ZHOU - Undetected ECHO TOP value is modified from SPVAL to -5000. 15-xx-xx S. Moorthi - reduced memory version 15-11-03 S Moorthi - fix a bug in "RELATIVE HUMIDITY ON MDLSURFACES" sectio logic 19-10-30 Bo CUI - REMOVE "GOTO" STATEMENT 20-03-24 J MENG - remove grib1 20-05-20 J MENG - CALRH unification with NAM scheme 20-11-10 J MENG - USE UPP_MATH MODULE 20-11-10 J MENG - USE UPP_PHYSICS MODULE 21-04-01 J MENG - COMPUTATION ON DEFINED POINTS ONLY 21-07-07 J MENG - 2D DECOMPOSITION 22-05-25 Y Mao - Add WAFS icing/turbulence on pressure levels 22-09-22 L Zhang - ADD NO3 and NH4 output for UFS-Aerosols model 22-10-20 W Meng - Bug fix for cloud fraction and vertically integrated liquid 22-11-08 W Meng - Output hourly averaged PM2.5 and O3 for AQM model only (aqf_on) 22-11-16 E James - Adding dust from RRFS 23-02-10 E James - Adding an extra IGET value to if statement for NGMSLP calculation 23-02-23 E James - Adding coarse PM from RRFS 23-03-03 S Trahan - Avoid out-of-bounds access in U2H & V2H by using USTORE & VSTORE with halo bounds 23-04-04 | Li(Kate Zhang) |Add namelist optoin for CCPP-Chem (UFS-Chem) 23-06-26 | W Meng | Output composite radar reflectivity when GFS uses Thompson MP USAGE: CALL MDLFLD INPUT ARGUMENT LIST:
OUTPUT ARGUMENT LIST: NONE
OUTPUT FILES: NONE
SUBPROGRAMS CALLED: UTILITIES: BOUND - BOUND ARRAY ELEMENTS BETWEEN LOWER AND UPPER LIMITS. SCLFLD - SCALE ARRAY ELEMENTS BY SCALAR CONSTANT. NGMSLP - COMPUTE SLP USING STANDARD NMC REDUCTION METHOD. CALPOT - COMPUTE POTENTIAL TEMPERATURE. CALRH - COMPUTE RELATIVE HUMIDITY. CALDWP - COMPUTE DEWPOINT TEMPERATURE. CALMCVG - COMPUTE MOISTURE CONVERGENCE. CALVOR - COMPUTE ABSOLUTE VORTICITY. CALSTRM - COMPUTE GEOSTROPHIC STREAMFUNCTION. CALMICT_new - COMPUTES CLOUD FIELDS AND RADAR REFLECTIVITY FACTOR FOR FERRIER-ALIGO CALMICT_old - COMPUTES CLOUD FIELDS AND RADAR REFLECTIVITY FACTOR FOR OTHER FERRIER OPTIONS LIBRARY: COMMON - RQSTFLD CTLBLK
ATTRIBUTES: LANGUAGE: FORTRAN MACHINE : CRAY C-90
Definition at line 90 of file MDLFLD.f.
References bound(), caldwp(), calgust(), calmcvg(), calmict_old(), calpot(), calrch(), calstrm(), ngmslp(), and smooth().