# This is the cmake build file for the tests directory of the UPP project.
#
# Alyson Stahl, 10/2025

message(STATUS "Building test directory...")

# This function builds, links, and runs a Fortran test program.
function(create_test name)
  add_executable(${name} ${name}.f90)
  target_link_libraries(${name} PRIVATE upp::upp)
  set_target_properties(${name} PROPERTIES LINKER_LANGUAGE Fortran)
  add_test(NAME ${name} COMMAND ${name})
endfunction()

create_test(test_dewpoint)
create_test(test_bound)
create_test(test_caldrg)
create_test(test_calstrm)
create_test(test_callcl)
create_test(test_calpot)
create_test(test_calvis)
create_test(test_calvis_gsd)
create_test(test_calwxt_dominant)
create_test(test_calthte)
create_test(test_calvessel)
create_test(test_calwxt_explicit)
create_test(test_ttblex)
create_test(test_wetfrzlvl)
create_test(test_zensun)
create_test(test_geo_zenith_angle)
create_test(test_icaoheight)
create_test(test_gpvs)
create_test(test_etamp_q2f)
create_test(test_etcalc)
create_test(test_fgamma)
create_test(test_canres)
create_test(test_clmax)
create_test(test_cldfrac_zhao)
create_test(test_mdl2sigma2)
create_test(test_mixlen)
create_test(test_msfps)
create_test(test_para_range)
create_test(test_poleavg)
create_test(test_smooth)
create_test(test_sclfld)
create_test(test_spline)
create_test(test_snfrac)
create_test(test_snfrac_gfs)
