#!/bin/ksh
#
set -x

# August 2005: Hui-Ya Chuang, NCEP: This script uses 
# NCEP's Unipost to post processes WRF native model 
# output, and uses copygb to horizontally interpolate posted 
# output from native A-E to a regular projection grid. 
#
# July 2006: Meral Demirtas, NCAR/DTC: Added new "copygb" 
# options and revised some parts for clarity. 
#
#--------------------------------------------------------
# This script performs 3 jobs:
#
# 1. Run Unipost
# 2. Run copygb to horizontally interpolate output from 
#    native A-E to a regular projection grid
# 3. Run GrADS to plot results.
#--------------------------------------------------------

#--- EDIT HERE --------------------------------------------------------
# TOP_DIR - where you put the UPP build directory
# DOMAINPATH - where do you want me to do my work
# WRFPATH - Where do you have a version of WRF compiled
# *** Datafile is entered below - it may reference these variables
# dyncore - set to the model used 
#----------------------------------------------------------------------
export TOP_DIR=/home/username
export DOMAINPATH=${TOP_DIR}/DOMAINS/test_case
export WRFPATH=${WRF_DIR}

export UNIPOST_HOME=${TOP_DIR}/UPPV2.0
export POSTEXEC=${UNIPOST_HOME}/bin
export SCRIPTS=${UNIPOST_HOME}/scripts

#Specify Dyn Core (ARW or NMM in upper case)
dyncore="NMM"

if [ $dyncore = "NMM" ]; then
   export tag=NMM
elif [ $dyncore = "ARW" ]; then
   export tag=NCAR
else
    echo "${dyncore} is not supported. Edit script to choose ARW or NMM dyncore."
    exit
fi

#--- EDIT HERE --------------------------------------------------------
# startdate = Forecast start date
# fhr =  first forecast hour to be post-processed
# lastfhr = last forecast hour to be post-processed
# incrementhr = the incement (in hours) between forecast files
#   DO NOT SET incrementhr TO ZERO - infinite loop will result
#----------------------------------------------------------------------

export startdate=2005012300
export fhr=00
export lastfhr=18
export incrementhr=03

# cd to working directory
cd ${DOMAINPATH}/postprd

# GrADS's fonts for plotting.
ln -sf ${SCRIPTS}/cbar.gs .

# Link Ferrier's microphysic's table and Unipost control file, 
ln -fs ${WRFPATH}/run/ETAMPNEW_DATA eta_micro_lookup.dat

# Get local copy of parm file
# For GRIB1 the code uses wrf_cntrl.parm to select variables for output
#   the available fields are set at compilation
# For GRIB2 the code uses postcntrl.xml to select variables for output
#   the available fields are defined in post_avlbflds.xml -- while we
#   set a link to this file for reading during runtime it is not typical
#   for one to update this file, therefore the link goes back to the
#   program directory - this is true for params_grib2_tbl_new also - a
#   file which defines the GRIB2 table values
ln -fs ../parm/wrf_cntrl.parm wrf_cntrl.parm
ln -fs ${UNIPOST_HOME}/parm/post_avblflds.xml post_avblflds.xml
ln -fs ../parm/postcntrl.xml postcntrl.xml
ln -fs ${UNIPOST_HOME}/src/lib/g2tmpl/params_grib2_tbl_new params_grib2_tbl_new

# link coefficients for crtm2 (simulated GOES)
CRTMDIR=${UNIPOST_HOME}/src/lib/crtm2/coefficients
ln -fs $CRTMDIR/EmisCoeff/Big_Endian/EmisCoeff.bin           ./
ln -fs $CRTMDIR/AerosolCoeff/Big_Endian/AerosolCoeff.bin     ./
ln -fs $CRTMDIR/CloudCoeff/Big_Endian/CloudCoeff.bin         ./
ln -fs $CRTMDIR/SpcCoeff/Big_Endian/imgr_g12.SpcCoeff.bin    ./
ln -fs $CRTMDIR/TauCoeff/Big_Endian/imgr_g12.TauCoeff.bin    ./
ln -fs $CRTMDIR/SpcCoeff/Big_Endian/imgr_g11.SpcCoeff.bin    ./
ln -fs $CRTMDIR/TauCoeff/Big_Endian/imgr_g11.TauCoeff.bin    ./
ln -fs $CRTMDIR/SpcCoeff/Big_Endian/amsre_aqua.SpcCoeff.bin  ./
ln -fs $CRTMDIR/TauCoeff/Big_Endian/amsre_aqua.TauCoeff.bin  ./
ln -fs $CRTMDIR/SpcCoeff/Big_Endian/tmi_trmm.SpcCoeff.bin    ./
ln -fs $CRTMDIR/TauCoeff/Big_Endian/tmi_trmm.TauCoeff.bin    ./
ln -fs $CRTMDIR/SpcCoeff/Big_Endian/ssmi_f15.SpcCoeff.bin    ./
ln -fs $CRTMDIR/TauCoeff/Big_Endian/ssmi_f15.TauCoeff.bin    ./
ln -fs $CRTMDIR/SpcCoeff/Big_Endian/ssmis_f20.SpcCoeff.bin   ./
ln -fs $CRTMDIR/TauCoeff/Big_Endian/ssmis_f20.TauCoeff.bin   ./
ln -fs $CRTMDIR/SpcCoeff/Big_Endian/ssmis_f17.SpcCoeff.bin   ./
ln -fs $CRTMDIR/TauCoeff/Big_Endian/ssmis_f17.TauCoeff.bin   ./

#--- EDIT HERE --------------------------------------------------------
# tmmark is an variable used as the file extention of the output
#    filename .GrbF is used if this variable is not set
# COMSP is a variable used as the initial string of the output filename
#----------------------------------------------------------------------
export tmmark=tm00
export MP_SHARED_MEMORY=yes
export MP_LABELIO=yes

#######################################################
# 1. Run Unipost
#
# The Unipost is used to read native WRF model 
# output and put out isobaric state fields and derived fields.
#######################################################

export NEWDATE=$startdate

while [ $((10#${fhr})) -le $((10#${lastfhr})) ] ; do

# Formatted fhr for filenames
fhr=`printf "%02i" ${fhr}`

NEWDATE=`${POSTEXEC}/ndate.exe +$((10#${fhr})) $startdate`

YY=`echo $NEWDATE | cut -c1-4`
MM=`echo $NEWDATE | cut -c5-6`
DD=`echo $NEWDATE | cut -c7-8`
HH=`echo $NEWDATE | cut -c9-10`

echo 'NEWDATE' $NEWDATE
echo 'YY' $YY


#--- EDIT HERE --------------------------------------------------------
# Update domains
# ie. for domain in d01 d02 d03
for domain in d01 
do

#--- EDIT HERE --------------------------------------------------------
# Create input file for Unipost
#   First line is where your wrfout data is
#   Second line is the format
#   ** FOR GRIB2 the thrid line is "grib2" and the next 2 lines move down **
#   Third line is the time for this process file
#   Forth line is a tag identifing the model
#----------------------------------------------------------------------
cat > itag <<EOF
../wrfprd/wrfout_${domain}_${YY}-${MM}-${DD}_${HH}:00:00
netcdf
${YY}-${MM}-${DD}_${HH}:00:00
${tag}
EOF

#-----------------------------------------------------------------------
#   Run unipost.
#-----------------------------------------------------------------------
rm fort.*

ln -sf wrf_cntrl.parm fort.14

#--- EDIT HERE --------------------------------------------------------
# Uncomment unipost.exe you want to run 
#   mpirun for MPI dmpar compile -- UPDATE FOR YOUR SYSTEM!!! ** FOR
#      now there are two environment variables tmmark and COMSP
#   unipost.exe for serial compile
#----------------------------------------------------------------------
# Serial run command
  ${POSTEXEC}/unipost.exe > unipost_${domain}.$fhr.out 2>&1
#
# dmpar run
mpirun -np 1 ${POSTEXEC}/unipost.exe > unipost_${domain}.$fhr.out 2>&1
#
# Debugging a specific fhr with a debugger
#if [[ $((10#${fhr})) -eq 3 ]]; then
#  mpirun -np 1 -dbg=pgdbg ${POSTEXEC}/unipost.exe > unipost_${domain}.$fhr.out 2>&1
#else
#  mpirun -np 1 ${POSTEXEC}/unipost.exe > unipost_${domain}.$fhr.out 2>&1
#fi
#
# This prefix was given in the wrf_cntl.parm file(GRIB1) or
# postcntrl.xml(GRIB2)
mv WRFPRS$fhr.${tmmark} WRFPRS_${domain}.${fhr}

#
#----------------------------------------------------------------------
#   End of unipost job
#----------------------------------------------------------------------

ls -l WRFPRS_${domain}.${fhr}
err1=$?

if test "$err1" -ne 0
then

echo 'UNIPOST FAILED, EXITTING'
exit

fi

if [ $dyncore = "NMM" ]; then

#######################################################################
# 2. Run copygb
# 
# Copygb interpolates unipost output from its native 
# grid to a regular projection grid. The package copygb 
# is used to horizontally interpolate from one domain 
# to another, it is necessary to run this step for wrf-nmm 
# (but not for wrf-arw) because wrf-nmm's computational 
# domain is on rotated Arakawa-E grid
#
# Copygb can be run in 3 ways as explained below. 
# Uncomment the preferable one.
#
#----------------------------------------------------------------------
#
# Option 1: 
# Copygb is run with a pre-defined AWIPS grid 
# (variable $gridno, see below) Specify the grid to 
# interpolate the forecast onto. To use standard AWIPS grids 
# (list in  http://wwwt.emc.ncep.noaa.gov/mmb/namgrids/ or 
# or http://www.nco.ncep.noaa.gov/pmb/docs/on388/tableb.html),
# set the number of the grid in variable gridno below.
# To use a user defined grid, see explanation above copygb.exe command.
#
#export gridno=212
#
#${POSTEXEC}/copygb.exe -xg${gridno} WRFPRS_${domain}.${fhr} wrfprs_${domain}.${fhr}
#
#----------------------------------------------------------------------
#
#  Option 2: 
#  Copygb ingests a kgds definition on the command line.
#${POSTEXEC}/copygb.exe -xg"255 3 109 91 37748 -77613 8 -71000 10379 9900 0 64 42000 42000" WRFPRS_${domain}.${fhr} wrfprs_${domain}.${fhr}
#
#----------------------------------------------------------------------
#
#  Option 3: 
#  Copygb can ingests contents of files too. For example:
#     copygb_gridnav.txt or copygb_hwrf.txt through variable $nav.
# 
#  Option -3.1:
#    To run for "Lambert Comformal map projection" uncomment the following line
#
 read nav < 'copygb_gridnav.txt'
#
#  Option -3.2:
#    To run for "lat-lon" uncomment the following line 
#
#read nav < 'copygb_hwrf.txt'
#
export nav
#
${POSTEXEC}/copygb.exe -xg"${nav}" WRFPRS_${domain}.${fhr} wrfprs_${domain}.${fhr}
#
# (For more info on "copygb" see WRF-NMM User's Guide, Chapter-7.)
#----------------------------------------------------------------------

# Check to see whether "copygb" created the requested file.

ls -l wrfprs_${domain}.${fhr}
err1=$?

if test "$err1" -ne 0
then

echo 'copygb FAILED, EXITTING'
exit

fi

#----------------------------------------------------------------------
#   End of copygb job
#----------------------------------------------------------------------
elif [ $dyncore = "ARW" ]; then
    ln -s WRFPRS_${domain}.${fhr} wrfprs_${domain}.${fhr}
fi

#######################################################
# 3. Run GrADS to plot results.
# Use GrADS to first create GrADS control and index 
# (or bitmap) files and then plot various fields.
#######################################################

rm -f wrfprs_${domain}_${fhr}.ctl

grib2ctl.pl -verf wrfprs_${domain}.${fhr} > wrfprs_${domain}_${fhr}.ctl

# GrADS has problem plotting vorticity because it's not posted on all 39 pressure levels
# modify control file to define a 500 mb vorticity field

cp wrfprs_${domain}_${fhr}.ctl wrfprs_${domain}_${fhr}.ctl_org

# creating GrADS index or bitmap file

gribmap -i wrfprs_${domain}_${fhr}.ctl

#grads << EOF

cat > plotgrads << EOF
'open wrfprs_${domain}_${fhr}.ctl'
'set display color white'
'set mpdset hires'
'set gxout shaded'
'set clevs 0.01 1 3 6 9 12 15 18 21'
'set rbcols 0 10 13 5 11 4 8 2 6 9'
'd APCPsfc'
'cbar'
'set gxout contour'
'set ccolor 9'
'set cint 2'
'd MSLETmsl/100'
'draw title Accumulated Total precipitation (shaded-mm) & MSLP (hPa)'
'printim Sfcmap${fhr}_${domain}_GrADS.gif gif'

'clear'
'set gxout shaded'
'set clevs 70 75 80 85 90 92 94 96 98 99'
'set rbcols 0 10 13 5 11 4 8 6 2 9 15'
'set lev 850'
'd RHprs'
'cbar'
'draw title RH at 850 hPa (shaded-%)'
'printim 850mbRH${fhr}_${domain}_GrADS.gif gif'

'clear'
'set gxout shaded'
'set clevs -20 -15 -10 -5 0 5 10 15 20'
'set rbcols 0 4 11 15 13 8 6 2 9 15'
'set lev 850'
'd TMPprs-273'
'cbar'
'd ugrdprs;skip(vgrdprs,5)'
'draw title Temperature (shaded-C) & winds (m/s) at 850 hPa'
'printim 850mbTempandWind${fhr}_${domain}_GrADS.gif gif'

'clear'
'set gxout shaded'
'set clevs 1.6 2.0 2.4 2.8 3.2 3.6 4'
'set rbcols 0 10 13 5 11 4 8 2'
'set lev 500'
'd ABSVprs*10000'
'cbar'
'set gxout contour'
'set ccolor 7'
'd HGTprs'
'draw title Abs Vort (shaded-10^5 s-1) & geo hgt (contour-m) at 500 hPa'
'printim 500mbHandVort${fhr}_${domain}_GrADS.gif gif'

'clear'
'set gxout shaded'
'set clevs 20 25 30 35 40 45 50'
'set rbcols 0 10 13 5 11 4 8 6'
'set lev 250'
'd sqrt(ugrdprs*ugrdprs+vgrdprs*vgrdprs)'
'cbar'
'set gxout contour'
'set ccolor 7'
'd HGTprs'
'draw title Speed (shaded-m/s) & geo height (contour-m) at 250 hPa'
'printim 250mbWindandH${fhr}_${domain}_GrADS.gif gif'
'quit'
EOF

gradsc -blc "run plotgrads"

#----------------------------------------------------------------------
#   End of GrADS job
#----------------------------------------------------------------------

done

fhr=$((10#${fhr}+$((${incrementhr}))))

NEWDATE=`${POSTEXEC}/ndate.exe +$((10#${fhr})) $startdate`

done

date
echo "End of Output Job"
exit
