#!/bin/ksh 

export PS4='$SECONDS + '
date
set -xa

export MP_EUIDEVELOP=min
export KMP_STACKSIZE=2048m
export MPICH_ALLTOALL_THROTTLE=0
export MP_SINGLE_THREAD=yes
export MP_EAGER_LIMIT=65536
export MP_USE_BULK_XFER=no
export MP_COLLECTIVE_OFFLOAD=no
export MP_SHARED_MEMORY=yes
export MP_MPILIB=mpich2
export MP_LABELIO=yes

#Specify whether the run is production or development
#
export envir=${envir:-prod}

####################################
# Specify version numbers
####################################
export post_ver=${post_ver:-v5.0.0}
export crtm_ver=${crtm_ver:-v2.0.6}
export gsm_ver=${gsm_ver:-v12.0.0}

####################################
# obtain unique process id (pid) and make temp directory
####################################
export pid=$$
export DATA_IN=${DATA_IN:-/tmpnwprd1}
export DATA=$DATA_IN/${job}.${pid}
mkdir $DATA
cd $DATA

export cycle=t${cyc}z
export GRIBVERSION=${GRIBVERSION:-'grib2'}

####################################
# Specify NET and RUN Name and model
####################################
export NET=gfs
export RUN=gfs

#########################################
# Specify non prod environment variables
#########################################
if [ $envir != prod ]; then
  export jlogfile=/com/logs/${envir}/jlogfile
  export DBNROOT=/nwprod/spa_util/fakedbn
fi

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-/com/logs/jlogfiles/jlogfile.${job}.${pid}}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

####################################
# SAVEGES  - Copy Files From TMPDIR to $GESdir
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
# RERUN    - Rerun posts from beginning (default no)
# VERBOSE  - Specify Verbose Output in global_postgp.sh
####################################
export SAVEGES=${SAVEGES:-YES}
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDDBN_GB2=${SENDDBN_GB2:-YES}
export RERUN=${RERUN:-NO}
export VERBOSE=${VERBOSE:-YES}

####################################
# Specify Execution Areas
####################################
export HOMEGLOBAL=${HOMEGLOBAL:-/nwprod}
export EXECGLOBAL=${EXECGLOBAL:-$HOMEGLOBAL/exec}
export USHGLOBAL=${USHGLOBAL:-$HOMEGLOBAL/ush}
export FIXGLOBAL=${FIXGLOBAL:-$HOMEGLOBAL/fix}
export SCRGLOBAL=${SCRGLOBAL:-$HOMEGLOBAL/scripts}
export UTILGLOBAL=${UTILGLOBAL:-$HOMEGLOBAL/util}
export PARMGLOBAL=${PARMGLOBAL:-$HOMEGLOBAL/parm}

export HOMECRTM=${HOMECRTM:-/nwprod/lib/crtm/${crtm_ver}}
export FIXCRTM=${FIXCRTM:-$HOMECRTM/sorc/fix}

export HOMEPOST=${HOMEPOST:-/nw${envir}/ncep_post.${post_ver}}
export EXECPOST=${EXECPOST:-$HOMEPOST/exec}
export FIXPOST=${FIXPOST:-$HOMEPOST/fix}
export USHPOST=${USHPOST:-$HOMEPOST/ush}
export SCRPOST=${SCRPOST:-$HOMEPOST/scripts}
export UTILPOST=${UTILPOST:-$HOMEPOST/util}
export PARMPOST=${PARMPOST:-$HOMEPOST/parm}

export HOMEGSM=${HOMEGSM:-/nw${envir}/gsm.${gsm_ver}}
export EXECGSM=${EXECGSM:-$HOMEGSM/exec}
export FIXGSM=${FIXGSM:-$HOMEGSM/fix}
export USHGSM=${USHGSM:-$HOMEGSM/ush}
export SCRGSM=${SCRGSM:-$HOMEGSM/scripts}
export UTILGSM=${UTILGSM:-$HOMEGSM/util}
export PARMGSM=${PARMGSM:-$HOMEGSM/parm}

export HOMEgfs=${HOMEgfs:-/nw${envir}/gfs.${gfs_ver}}
export USHgfs=${USHgfs:-$HOMEgfs/ush/}

export HOMEUTIL=${HOMEUTIL:-/nw${envir}/util.${util_ver}}
export EXECUTIL=${EXECUTIL:-$HOMEUTIL/exec}
export FIXUTIL=${FIXUTIL:-$HOMEUTIL/fix}

export ERRSCRIPT=err_chk
export LOGSCRIPT=startmsg
export REDOUT='1>>'
export REDERR='2>'

##############################
# Set up the UTILITIES
##############################
export SIGHDR=${SIGHDR:-$EXECGSM/global_sighdr}
export utilscript=${utilscript:-$HOMEUTIL/ush}
export COPYGB=${COPYGB:-$EXECUTIL/copygb}
export COPYGB2=${COPYGB2:-$EXECUTIL/copygb2}
export GRBINDEX=${GRBINDEX:-$EXECUTIL/grbindex}
export GRBINDEX2=${GRBINDEX2:-$EXECUTIL/grb2index}
export WGRIB=${WGRIB:-$EXECUTIL/wgrib}
export WGRIB2=${WGRIB2:-$EXECUTIL/wgrib2}
export CNVGRIB=${CNVGRIB:-$EXECUTIL/cnvgrib}
export CNVGRIB21=${CNVGRIB21:-$EXECUTIL/cnvgrib21_gfs}

##############################
# Run setup to initialize working directory and utility scripts
##############################
#$utilscript/setup.sh

##############################
# Run setpdy and initialize PDY variables
##############################
#$utilscript/setpdy.sh
#. PDY

##############################################
# Define COM directories
##############################################
export COMIN=${COMIN:-/com/${NET}/${envir}/${RUN}.${PDY}}
export COMOUT=${COMOUT:-/com/${NET}/${envir}/${RUN}.${PDY}}
mkdir -m 775 -p $COMOUT

##############################################
# Define GES directories
##############################################
gespath=/nwges/${envir}
export GESdir=$gespath/${RUN}.${PDY}
mkdir -m 775 -p $GESdir

####################################
# Specify Special Post Vars
####################################

export POSTGPVARS="KPO=47,PO=1000.,975.,950.,925.,900.,875.,850.,825.,800.,775.,750.,725.,700.,675.,650.,625.,600.,575.,550.,525.,500.,475.,450.,425.,400.,375.,350.,325.,300.,275.,250.,225.,200.,175.,150.,125.,100.,70.,50.,30.,20.,10.,7.,5.,3.,2.,1.,"

export CHGRESEXEC=${CHGRESEXEC:-$EXECGSM/global_chgres}
export CHGRESSH=${CHGRESSH:-$USHGSM/global_chgres.sh}
export CHGRESTHREAD=32
export OVERPARMEXEC=$EXECGLOBAL/overparm_grib
export POSTGPEXEC=${POSTGPEXEC:-$EXECPOST/ncep_post}

if [ $GRIBVERSION = grib1 ]; then
 export IGEN_ANL=81
 export IGEN_FCST=96
 export CTLFILE=${PARMPOST}/gfs_cntrl.parm
elif [ $GRIBVERSION = grib2 ]; then
 export IGEN_ANL="anal_gfs"
 export IGEN_FCST="gfs_avn"
 export IGEN_GFS="gfs_avn"
fi

###############################
# Parameters for chgres to use
###############################
export LSOIL=4
export LATCH=8

#######################################################
# Define Variables for testing
# This is for the convenience of parallel testing
# Should be removed when moving to /nwprod
#######################################################
#FHOUR_HIGH=180

#if [ "$post_times" = "anl" ]
#then
#  export LEVS=64
#  export JCAP=382

#elif [ "$post_times" -le $FHOUR_HIGH ]
#then
#  export LEVS=64
#  export JCAP=382
#else
#  export LEVS=64
#  export JCAP=190
#fi

#######################################
# Specify Restart File Name to Key Off
#######################################
restart_file=$COMIN/${RUN}.t${cyc}z.logf

####################################
# Specify Timeout Behavior of Post
#
# SLEEP_TIME - Amount of time to wait for
#              a restart file before exiting
# SLEEP_INT  - Amount of time to wait between
#              checking for restart files
####################################
export SLEEP_TIME=900
export SLEEP_INT=5

env

##########################################################
# Specify variable to directly output pgrb2 files for GFS
##########################################################
export IDRT=0 # IDRT=0 is setting for outputting grib files on lat/lon grid
export res=0p25
if [ $IDRT -eq 0 ] ; then
# 0.125 deg
  if [ $res = "0p125" ] ; then
    export LONB=2880
    export LATB=1441
    export grid='255 0 2880 1441 90000 0 128 -90000 359875 125 125 0'
# 0.25 deg
  elif [ $res = "0p25" ] ; then
    export LONB=1440
    export LATB=721
    export grid='255 0 1440 721 90000 0 128 -90000 359750 250 250 0'
# 0.5 deg
  elif [ $res = "0p50" ] ; then
    export LONB=720
    export LATB=361
    export grid='255 0 720 361 90000 0 128 -90000 359500 500 500 0'
  fi
fi

#############################################################
# Execute the regular master ncep post script
${SCRPOST}/exgfs_nceppost.sh.ecf
#############################################################

if [ $post_times -eq 84  ]
then
    echo "`hostname`  --  `date`" > $COMOUT/where_ibm_${RUN}_post84_ran.${cycle}
fi

##############################
# Remove the Temporary working directory
##############################
cd /tmpnwprd1
rm -rf $DATA

date
