matchedNode = []
for (label in pullRequest.labels) {
   listOfLabelNodeNames = jenkins.model.Jenkins.instance.nodes.collect {
   node -> node.getLabelString().contains(label) ? node.name : null

   if ((label.matches(node.getLabelString()+"-(.*)"))) {
     matchedNode += node.getLabelString()
   }
 }
}

modifiedLabels = matchedNode.collect{"'" + it + "'"} 
def generateStage(nodeLabel) {
    return {
        stage("Running on ${nodeLabel}") {
            node(nodeLabel) {
	      dir (${nodeLabel}) {
               cleanWs()
               checkout scm
               script {
                 try {
                    echo "Running on ${nodeLabel}"
                       sh '''
                       pwd
                       cd tests
                       export machine=${NODE_NAME}
                       export PATH=$PATH:~/bin
                       echo $CHANGE_ID
                       export SSH_ORIGIN=$(curl --silent https://api.github.com/repos/NOAA-EMC/UPP/pulls/$CHANGE_ID | jq -r '.head.repo.ssh_url')
                       export FORK_BRANCH=$(curl --silent https://api.github.com/repos/NOAA-EMC/UPP/pulls/$CHANGE_ID | jq -r '.head.ref')

                          if [[ $machine =~ "Hercules" ]]
                          then
                          echo "Running regression tests on $machine"
                            export dprefix=/work2/noaa/$ACCNR/$USER
			    cd $WORKSPACE/ci
                            sed "s|/noaa/stmp/|/noaa/$ACCNR/stmp/|g" -i rt.sh
                            export ACCNR=epic
                            ./rt.sh -a ${ACCNR} | tee $WORKSPACE/tests/logs/RT-run-$machine.log
                            cd $WORKSPACE/tests/logs/
                            cp rt.log.HERCULES /work/noaa/epic/role-epic/jenkins/workspace
                            git remote -v
                            git fetch --no-recurse-submodules origin
                            git reset FETCH_HEAD --hard
                            cd .. && cd .. && cd ..
                            cp rt.log.HERCULES $WORKSPACE/tests/logs/
                            cd $WORKSPACE/tests/
                          elif [[ $machine =~ "Orion" ]]
                          then
                           echo "Running regression tests on $machine"
                            export dprefix=/work2/noaa/$ACCNR/$USER
			    cd $WORKSPACE/ci
                            sed "s|/noaa/stmp/|/noaa/$ACCNR/stmp/|g" -i rt.sh
                            ./rt.sh -a ${ACCNR} | tee $WORKSPACE/tests/logs/RT-run-$machine.log
                             cd $WORKSPACE/tests/logs/
                             cp rt.log.ORION /work/noaa/epic/role-epic/jenkins/workspace
                             git remote -v
                             git fetch --no-recurse-submodules origin
                             git reset FETCH_HEAD --hard
                             cd .. && cd .. && cd ..
			     cp rt.log.ORION $WORKSPACE/tests/logs/
			     cd $WORKSPACE/tests/
                          elif [[ $machine =~ "Hera" ]]
                          then
                           echo "Running regression tests on $machine"
                             export ACCNR=epic
			     cd $WORKSPACE/ci
                             ./rt.sh -a ${ACCNR} | tee $WORKSPACE/tests/logs/RT-run-$machine.log
			     cd $WORKSPACE/tests/logs
			     cp rt.log.HERA /scratch2/NAGAPE/epic/role.epic/jenkins/workspace
			     git remote -v
                             git fetch --no-recurse-submodules origin
                             git reset FETCH_HEAD --hard
                             cd .. && cd .. && cd ..
			     cp rt.log.HERA $WORKSPACE/tests/logs/
			     cd $WORKSPACE/tests/
                          else
                           echo "Running regression tests on $machine"
                           ./rt.sh -a ${ACCNR} | tee $WORKSPACE/tests/logs/RT-run-$machine.log
                          fi

                      git config user.email "ecc.platform@noaa.gov"
                      git config user.name "epic-cicd-jenkins"
                      export machine_name_logs=$(echo $machine | awk '{ print toupper($1) }')
                      echo "Testing concluded...removing labels for $machine from $GIT_URL"
                      git remote -v | grep -w sshorigin > /dev/null 2>&1 && git remote remove sshorigin > /dev/null 2>&1
                      git remote add sshorigin $SSH_ORIGIN > /dev/null 2>&1
                      git add logs/rt.log.$machine_name_logs
                      git commit -m "[AutoRT] $machine Job Completed.\n\n\n on-behalf-of @ufs-community <ecc.platform@noaa.gov>"
                      git pull sshorigin $FORK_BRANCH
                      git push sshorigin HEAD:$FORK_BRANCH

                      tar --create --gzip --verbose --dereference --file "${machine_name_logs}.tgz" ${WORKSPACE}/tests/logs/*.log

                      GIT_OWNER=$(echo $GIT_URL | cut -d '/' -f4)
                      GIT_REPO_NAME=$(echo $GIT_URL | cut -d '/' -f5 | cut -d '.' -f1)

                      curl --silent -X DELETE -H "Accept: application/vnd.github.v3+json" -H "Authorization: Bearer ${GITHUB_TOKEN}"  https://api.github.com/repos/${GIT_OWNER}/${GIT_REPO_NAME}/issues/${CHANGE_ID}/labels/$machine-RT
                        
                       '''
                  }
                  catch(err) {
                    sh '''
                      export machine=${NODE_NAME}
                      export CHANGE_ID=${CHANGE_ID}
                      export SSH_ORIGIN=$(curl --silent https://api.github.com/repos/NOAA-EMC/UPP/pulls/$CHANGE_ID | jq -r '.head.repo.ssh_url')
                      export FORK_BRANCH=$(curl --silent https://api.github.com/repos/NOAA-EMC/UPP/pulls/$CHANGE_ID | jq -r '.head.ref')
                      cd $WORKSPACE/tests
                      git config user.email "ecc.platform@noaa.gov"
                      git config user.name "epic-cicd-jenkins"
                      export machine_name_logs=$(echo $machine | awk '{ print toupper($1) }')
                      echo "Testing concluded...removing labels for $machine from $GIT_URL"
                      git remote -v | grep -w sshorigin > /dev/null 2>&1 && git remote remove sshorigin > /dev/null 2>&1
                      git remote add sshorigin $SSH_ORIGIN > /dev/null 2>&1

                      tar --create --gzip --verbose --dereference --file "${machine_name_logs}.tgz" ${WORKSPACE}/tests/logs/*.log

                      GIT_OWNER=$(echo $GIT_URL | cut -d '/' -f4)
                      GIT_REPO_NAME=$(echo $GIT_URL | cut -d '/' -f5 | cut -d '.' -f1)

                      curl --silent -X DELETE -H "Accept: application/vnd.github.v3+json" -H "Authorization: Bearer ${GITHUB_TOKEN}"  https://api.github.com/repos/${GIT_OWNER}/${GIT_REPO_NAME}/issues/${CHANGE_ID}/labels/$machine-RT
                    '''
                    currentBuild.result = 'FAILURE'
                  }
                }
              }
	     }
           }
       }
}

def parallelStagesMap = modifiedLabels.collectEntries {
    ["${it}" : generateStage(it)]
}

pipeline {
    agent none
    environment {
        ACCNR = 'epic'
        AWS_PROD_ACCOUNT_ID = credentials('AWS_PROD_ACCOUNT_ID')
        AWS_PROD_SNS_TOPIC = credentials('AWS_PROD_SNS_TOPIC')
        GITHUB_TOKEN = credentials('GithubJenkinsNew')
        GIT_URL = 'https://github.com/NOAA-EMC/UPP.git'
    }
    stages {
        stage('Run Regression Tests in Parallel') {
            steps {
                script {
                    parallel parallelStagesMap
                }
            }
        }       
    }   
}
