# This module looks for environment variables detailing where G2 lib is
# If variables are not set, G2 will be built from external source 
include(ExternalProject)
set(CMAKE_INSTALL_PREFIX ${PROJECT_BINARY_DIR})
ExternalProject_Add(NCEPLIBS-g2c 
  PREFIX ${PROJECT_BINARY_DIR}/NCEPLIBS-g2c
  CMAKE_ARGS
    -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
    -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
    -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
    -DCMAKE_Fortran_COMPILER=${CMAKE_Fortran_COMPILER}
    -DCMAKE_BUILD_TYPE=RELEASE
  SOURCE_DIR ${PROJECT_SOURCE_DIR}/NCEPLIBS-g2c 
  INSTALL_DIR ${CMAKE_INSTALL_PREFIX}
  BUILD_COMMAND make
  INSTALL_COMMAND make install
)
execute_process(COMMAND grep "set(VERSION" CMakeLists.txt WORKING_DIRECTORY ${PROJECT_SOURCE_DIR}/NCEPLIBS-g2c OUTPUT_VARIABLE LIBVERSION)
string(REPLACE "set(VERSION " "" LIBVERSION ${LIBVERSION})
string(REPLACE ")" "" LIBVERSION ${LIBVERSION})
string(REPLACE "\n" "" LIBVERSION ${LIBVERSION})
message("g2c version is ${LIBVERSION}")
set( G2_LIBRARY ${PROJECT_BINARY_DIR}/lib/libg2c_${LIBVERSION}.a )
if( CORE_BUILT )
    list( APPEND CORE_BUILT ${G2_LIBRARY} )
    list( APPEND EXT_BUILT NCEPLIBS-g2c )
else()
    set( CORE_BUILT ${G2_LIBRARY} )
    set( EXT_BUILT NCEPLIBS-g2c )
endif()

set( G2_LIBRARY_PATH ${G2_LIBRARY} CACHE STRING "G2 Library Location" )

