name: Intel
on: [push, pull_request, workflow_dispatch]

defaults:
  run:
    shell: bash -leo pipefail {0}

# Cancel in-progress workflows when pushing to a branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Intel:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compilers: ["oneapi", "classic"]

    steps:
      - name: "Install Intel"
        uses: NOAA-EMC/ci-install-intel-toolkit@develop
        with:
          oneapi-version: 2023.2.1
          compiler-setup: ${{ matrix.compilers }}
          install-mpi: true
          mpi-wrapper-setup: ${{ matrix.compilers }}
          
      - name: install-dependencies
        run: |
          sudo apt-get update 
          sudo apt-get install libnetcdf-dev pkg-config 
          sudo apt-get install libopenblas-dev libpng-dev autotools-dev libaec-dev autoconf

      - name: build-netcdf
        uses: NOAA-EMC/ci-build-cmake-code@develop
        with:
          package-name: netcdf-fortran
          package-org: Unidata
          git-ref: v4.6.1

      - name: build-crtm
        uses: NOAA-EMC/ci-build-cmake-code@develop
        with:
          package-name: EMC_crtm
          package-org: NOAA-EMC
          git-ref: v2.3.0

      - name: build-g2tmpl
        uses: NOAA-EMC/ci-build-cmake-code@develop
        with:
          package-name: NCEPLIBS-g2tmpl
          package-org: NOAA-EMC

      - name: build-sigio
        uses: NOAA-EMC/ci-build-cmake-code@develop
        with:
          package-name: NCEPLIBS-sigio
          package-org: NOAA-EMC

      - name: build-dependencies
        uses: NOAA-EMC/ci-build-nceplibs@develop
        with:
          jasper-version: version-4.0.0
          bacio-version: develop
          w3emc-version: develop
          w3emc-cmake-args: -DBUILD_WITH_BUFR=OFF
          g2-version: v3.5.1
          ip-version: develop
          key-prefix: intel-1

      - name: checkout
        uses: actions/checkout@v4
        with:
          path: UPP

      - name: build
        run: |
          set -x
          cd UPP
          mkdir build && cd build
          cmake .. -DBUILD_WITH_NEMSIO=OFF -DCMAKE_INSTALL_PREFIX=../install \
            -DCMAKE_PREFIX_PATH="$GITHUB_WORKSPACE/nceplibs/netcdf-fortran;$GITHUB_WORKSPACE/nceplibs/jasper;$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-bacio;$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-w3emc;$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-ip;$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-g2;$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-g2tmpl;$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-sigio;$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-wrf_io;$GITHUB_WORKSPACE/nceplibs/EMC_crtm" 
          make VERBOSE=1
          make install

      - name: run-tests
        run: |
          cd UPP/build
          ctest --verbose --output-on-failure --rerun-failed